### ISSUE TITLE
Make contracts installable as pip package

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden-contracts#10]
To integrate this repo with other projects, we'll need a working `setup.py` that allows us to install the contracts as a pip package.

### Installable `setup.py`
working with `pip install -e .` and `py setup.py build` targets

### utility library
`setup.py` should also have a contract compilation target that'll build the ABI & bytecode. These should be available with a helper library to other projects. The idea is to get rid of `solc` dependency for all projects except this one.

Quick & dirty example
```
import raiden_contracts

registry_abi = raiden_contracts.get_abi('RegistryContract')
event_abi = raiden_contracts.get_event_abi('RegistryContract', ''SomethingHappenedEvent)
```

**Comment by palango** [comment]
Quick note as I stumbled into this as well: The bytecode of the `TokenNetworkRegistry` with all dependencies required 6283184 gas some days ago. This was to much to deploy it in a single block and we need to link it to the requirements during deployment. I haven't found a nice solution to that yet, but we should keep in mind that just the json created by `populus compile` (which includes all dependencies in the bytecode) is not enough.

**Comment by pcppcp** [comment]
ok then, I will also include a contract manager able to compile contracts using libraries address using `solc`. `solc` won't be a hard requirement, the library simply won't provide such functionality if compiler is not installed. Getting ABI from pre-compiled `contracts.json` will still be available.

**Comment by pcppcp** [comment]
Foxed by #159
