### ISSUE TITLE
Raiden Smart Contract Value Limits for Mainnet Release

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden-contracts#103]
For the Red Eyes release we want to put artificial limits on the smart contracts for security reasons.

- [x] Figure out the amount of limits that should be put and how they should be. Kind of difficult due to different value of each token. For now let's go with 100 tokens.

- [x] Implement the limits in the contracts

- [x] Add some tests for the contract limits

**Comment by pepae** [comment]
I made this as little helper sheet to judge the impact of the limit: https://docs.google.com/spreadsheets/d/1zybi5HpElVBoMTmYLMFwNv1T4VjCclHaiCsm6Li9atI/edit#gid=0 

Questions:


- Is USD 50k low enough for the upper barrier?
- Does USD 10 make sense as a "cut-off" point where below that you would implicitly "exclude" these tokens for practical use?

If we can answer both of these with yes, I'd argue that (given the sheet and the tokens we'd "exclude") that the 100 tokens limit wouldn't be too bad. If anything, I'd say I'd say it could even be 50 tokens and we wouldn't exclude too many "important" tokens.

**Comment by heikoheiko** [comment]
As all tokens of one token network are in the same contract, the limit per channel does not limit the total amount that is managed by the contracts. Is this intentional? 

Related: Is there a plan what happens if there is a bug and tokens are lost?

**Comment by christianbrb** [comment]
Duplicate with https://github.com/raiden-network/team/issues/54
