### ISSUE TITLE
Should the private keys be `bytes` instead of `str`?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1059]
https://github.com/raiden-network/raiden-contracts/pull/965#discussion_r291106738

Which type does the signing primitive expect?  If it expects `bytes` we should be using `bytes` everywhere.

**Comment by pirapira** [comment]
Or even `PrivateKey`.  But these changes break the ABI. So not doing now.

**Comment by karlb** [comment]
Done in https://github.com/raiden-network/raiden-contracts/pull/1396.
