### ISSUE TITLE
Investigate the origin and the purpose of Raiden Testnet Token

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1094]
Today @rakanalh mentioned a token called RTT (Raiden Testnet Token) https://ropsten.etherscan.io/token/0x0f114a1e9db192502e7856309cc899952b3db1ed#writeContract .

This issue keeps track of figuring out who deployed this for what purpose, and more importantly who is using it currently.

**Comment by karlb** [comment]
We don't use it. I don't see a benefit in researching this contracts past, so I'm closing this issue.
