### ISSUE TITLE
Upgrade web3.py and eth-tester

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1162]
`raiden-contracts` is currently using months-old version of web3.py. For a long time web3.py was making only alpha releases, but now 5.0.0 is available.  This issue keeps track of upgrading web3.py and eth-utils.  There was a previous attempt: https://github.com/raiden-network/raiden-contracts/pull/1153 but due to a close release of the client, the change was reverted.

This issue keeps track of doing the upgrades again.

The benefits are:
* eth-tester will support the newest protocol of Ethereum
* faster eth-tester
* clearer exceptions

**Comment by pirapira** [comment]
https://github.com/raiden-network/raiden-contracts/pull/1153 has been reverted, but should be applied again once the Alderaan is out.

**Comment by palango** [comment]
Fixed by #1339
