### ISSUE TITLE
Try interacting with ServiceRegistry on a test network

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1172]
We can deploy ServiceRegistry on a testnet and try to interact with them.

## Aim

* to see whether the deposit amount moves in a reasonable way
* to see whether the ServiceRegistry can run through some typical scenarios

## Scope

* the scope of this issue is still the dev using the contract alone
* (handing it out to others can happen later).

## Steps

1. choose scenarios
2. try a single scenario
3. try the other scenarios concurrently

**Comment by karlb** [comment]
This has been done as part of the Alderaan test process.
