### ISSUE TITLE
Maybe we don't need cooperativeSettle()?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1236]
instead participants can do `setTotalWithdraw()` twice.

---

However, this has a certain subtlety.  There must be a way for enabling Alice's withdrawal and Bob's withdrawal atomically.

**Comment by pirapira** [comment]
We can solve this problem by making one withdraw dependent on the other withdraw.  We'd introduce a withdrawal proof that's valid only after another withdrawal has happened.

1. Alice would sign "Bob can withdraw that only after Alice withdraws this".
2. Bob would sign "Alice can withdraw this."
3. Alice would withdraw this.
4. Then Bob withdraws that.

**Comment by hackaugusto** [comment]
why do the withdraws have to happen atomically?

**Comment by pirapira** [comment]
Otherwise, nobody will sign the other party's withdraw proof first.

**Comment by pirapira** [comment]
But @hackaugusto pointed out that Alice can give Bob a choice.  Sign the withdraw proof or get the channel closed.  (As happening always on Raiden: follow the protocol or get the channel closed).

**Comment by pirapira** [comment]
@hackaugusto 's idea does not eliminate this possibility.

1. Alice asks Bob to sign a withdraw proof ("otherwise I'll close the channel").
2. Bob signs Alice's withdraw proof and sends it to Alice
3. Alice withdraws
4. Bob asks Alice to sign a withdraw proof
5. Alice ignores Bob

**Comment by palango** [comment]
Closing for the linked issue above.
