### ISSUE TITLE
Invalid assertion

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1248]
Assertion should only check for things that you expect to be true. In OneToN.sol:102 the assertion can easily be false, by just passing in an expiration_block of 0. Easy fix: change to require.

**Comment by karlb** [comment]
I assume this refers to
```
assert(expiration_block > 0);
```

Just by itself, it could easily be false, as `expiration_block` is given as parameter to the function. But above the assert, we have 
```
require(block.number <= expiration_block, "IOU expired");
```
which makes sure that the assert will be true as long as block.number is greater than 0 (which should be safe to assume).

I would be ok with using a `require`, but `assert` should be ok, too. Are there any reasons for favoring one over the other?
