### ISSUE TITLE
Release process should check the onchain code

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1308]
`raiden` [does not run](https://github.com/raiden-network/raiden/issues/5122) when there is a difference between
* `data_X/contracts.json`'s `bin-runtime`
* what's deployed at `data_X/deployment*.json`

However, our CI doesn't find such differences.

Maybe the release procedure should contain a step to find such a discrepancy.

**Comment by Dominik1999** [comment]
We will close this since we test that before we release any new version.
