### ISSUE TITLE
Add tests for batch unlock - locked vs. unlocked varying amounts per participant

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#132]
A participant `P1`'s `locked_amount1` (from `P1`'s balance proof) actually contains:
- `amount_that_can_be_unlocked` - if the `secret` was revealed => `P2` must receive this amount
- `amount_that_cannot_be_unlocked` - if the `secret` was not revealed => `P1` must receive this amount back, because the transfer was never finalized.

We must add tests for the settlement calculations that will ensure we compute the locked amount properly, in a way that the batch unlock has enough tokens left in the contract for it to be resolved fairly.

Cases:
- a very high `amount_that_can_be_unlocked` with a very low `amount_that_cannot_be_unlocked`
- a very low `amount_that_can_be_unlocked` with a very high `amount_that_cannot_be_unlocked`

**Comment by loredanacirstea** [comment]
Test cases:

A. Both balance proofs are valid and are the last known balance proofs.

```
Participant P1
deposit1 = 10
withdrawn1 = 0
transferred1 = 0
locked1 = 25

Participant P2
deposit2 = 5
withdrawn2 = 0
transferred2 = 0
locked2 = 15
```
1.
- all secrets are revealed for the pending transfers P1 -> P2, `locked1` must be transferred to `P2`
- all secrets are revealed for the pending transfers P2 -> P1, `locked2` must be transferred to `P1`
2. 
- none of the secrets are revealed for the pending transfers P1 -> P2, `locked1` must be transferred to `P1`
- all secrets are revealed for the pending transfers P2 -> P1, `locked2` must be transferred to `P1`
3. 
- all secrets are revealed for the pending transfers P1 -> P2, `locked1` must be transferred to `P2`
- none of the secrets are revealed for the pending transfers P2 -> P1, `locked2` must be transferred to `P2`

Note: both 2 & 3 are needed, due to the current settlement algorithm, which computes the participant amounts based on whether `transferred1 + locked1` is >= or <= than `transferred2 + locked2`

B. One of the balance proofs is old. We take `P1`s balance proof as being outdated.

```
Participant P1
deposit1 = 10
withdrawn1 = 0
transferred1 = 0
locked1 = 25

Participant P2
deposit2 = 5
withdrawn2 = 0
transferred2 = 0
locked2 = 100
```
Same 1, 2, 3 cases as for A.

**Comment by loredanacirstea** [comment]
I have made a more detailed analysis about the settlement algorithm here: https://github.com/raiden-network/raiden-contracts/issues/188.

This issue is on hold until the issues raised in the above one are discussed.

**Comment by LefterisJP** [comment]
@loredanacirstea I think this can be closed right?

**Comment by loredanacirstea** [comment]
This is actually solved in https://github.com/raiden-network/raiden-contracts/pull/189
