### ISSUE TITLE
release branch `alderaan`

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1327]
If we separate `alderaan` from the `master` branch, we can make breaking changes on `master` even while stabilizing `alderaan`.  This issue keeps track of designing such branches, and write out when to do what on which branch.

* when we need to patch Alderaan deployments
* when we start deploying post-Alderaan contracts
* 

What properties must always hold on `alderaan`?

What properties must always hold on `master`?

**Comment by palango** [comment]
We use master as the release branch instead. We can still branch later.
