### ISSUE TITLE
Add the deployed block number in the smart contracts.

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden-contracts#1351]
There is no API provided by the Ethereum clients to determine the block at which the smart contract was deployed. This means the filters used by Raiden have to be on a larger range than necessary (i.e. starting from know point in time, like a hard fork), this is specially problematic for smart contracts that were not deployed by our scripts (for our deployments we store the metadata).

To fix the above, during the contract constructor, the block number should be saved, then the Raiden client can just query the smart contract and create filters accordingly.

**Comment by palango** [comment]
This is included in the deployment data, as available form `deployment_data = get_contracts_deployment_info(...)`
