### ISSUE TITLE
Include the address of the TokenNetworkRegistry in the TokenNetwork events

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden-contracts#136]
Issue to discuss the pros and cons of having the token network address in the token network events, as suggested by @nkbai 

> @hackaugusto I think that events of TokenNetwork.sol should add TokenNetworkRegistry address,
so raiden can filter and found Channel events much easier

https://github.com/raiden-network/raiden-contracts/pull/135#issuecomment-398353244

@nkbai your input is very welcome :)

**Comment by LefterisJP** [comment]
@nkbai Why do you want to add the `TokenNetworkRegistry` address to the `TokenNetwork` events? That will not help with channel filtering in any way.

**Comment by loredanacirstea** [comment]
Adding another event argument, probably `indexed` just adds gas cost to the transaction, with no real benefit in my opinion.

**Comment by nkbai** [comment]
@LefterisJP why most channel events of   raiden version 0.3 have registry address?
this registry_address  argument was add about a month ago ?

**Comment by LefterisJP** [comment]
@nkbai Version 0.3.0 is frozen. We can't edit previous versions. What do you mean? If you mean the latest master it was just added there for convenience of testing during the transition from the old to the new contracts. It is just temporary so that tests work as we change the code.

**Comment by loredanacirstea** [comment]
@nkbai , please reopen if you still think this is a good idea and provide some pros&cons arguments.
I am closing this, as we do not have this change in plan.
