### ISSUE TITLE
Add a function to the SecretRegistry for batching secret registration

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#139]
The Raiden client might need to register multiple secrets if the channel closes and there are pending locks with known secrets. Having a `registerSecretBatch` function would reduce gas cost.

**Comment by LefterisJP** [comment]
Moving this issue to the Testnet release. It's a contract addition so should be there 100%.

**Comment by jomuel** [comment]
Done (#166)
