### ISSUE TITLE
Verify all Alderaan contracts on https://verification.komputing.org/

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden-contracts#1391]
It would be nice to verify all contracts or even automate the process of verifying contracts on https://verification.komputing.org/ for the Alderaan contracts.

- [x] Verify all Alderaan contract
- [ ] (optional) Automate the process for the future

**Comment by czepluch** [comment]
A bit more in-depth documentation can be found here: https://github.com/ethereum/sourcify

**Comment by karlb** [comment]
Except for the lack of clear instructions, their UI is actually really nice to use! This will be a quick thing to do, so I'll do it right away.

**Comment by karlb** [comment]
I didn't do a full automation. When we do this for the next time, we can automate it. Here's the gist:

1. Collect files needed for verification (it always includes all sources, but their server is smart enough to pick out the right ones):
```sh
for contract in $(jq '.contracts | keys[]' raiden_contracts/data/contracts.json -r); do
    mkdir -p verify/$contract
    jq ".contracts.$contract.metadata" -r raiden_contracts/data/contracts.json > verify/$contract/metadata.json
    cp raiden_contracts/data/source/{lib,raiden,services}/* verify/$contract
done   
```
2. For each contract, look up the address in `raiden_contracts/data/deployment_{services_,}mainnet.json` and submit all files created in the previous step in `verify/$contract`.

**Comment by czepluch** [comment]
Can you send me the link to to the sources, once they're ready?

**Comment by karlb** [comment]
http://contractrepo.komputing.org/contract/1/0xa80aEc9eebD8058A1468e563C025999590F32C08
http://contractrepo.komputing.org/contract/1/0x1c62fF66aF8aaD410065E02338F5bFbbe23e1f10
http://contractrepo.komputing.org/contract/1/0x727DDdBD042d891180A252C7A20634a696A16925
http://contractrepo.komputing.org/contract/1/0x960f01E9E219E1c8564784a050fD1cA51651592D
http://contractrepo.komputing.org/contract/1/0x70f0c29b946E63803BD0Be796E17E47138668A68
http://contractrepo.komputing.org/contract/1/0x6d07A2ef8De5d7D48337510BCEb9FEEa5424b20c
