### ISSUE TITLE
how to avoid replay attack to a channel?

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden-contracts#141]
for a reopened channel on a tokennetwork.sol,  how to detect that a participant is submitting the balance proof of last version?
1. v1 channel: A-B open a channel, channel id is 0x000001
 2. some transfers between A,B,
3. close and settle 0x000001
4. reopen v2 channel, this channel id is also 0x000001
5. A use V1's balance proof to close this v2 channel.

**Comment by nkbai** [comment]
what about to use tokenetwork address, chain id, channel identifier and opened block number as the unique channel id?
user's signature of balance proof contains all these four arguments.

**Comment by nkbai** [comment]
cooperate settle and withdraw has the same problem too.

**Comment by loredanacirstea** [comment]
Correct, that is why I said `include it in the signed messages`. This block number should be included in all of them.
