### ISSUE TITLE
Allow 3rd parties to register new token networks

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-contracts#1416]
Currently, we limit the number of token networks and register the full number of allowed tokens at deployment time. We would like to open up the registration of additional token networks to 3rd parties.

### Who can register a token network?

Potential solutions:
* Everyone (problems see below)
* Parties whitelisted in the contracts
* Parties chosen by some DAO

### Problems with allowing anyone to register

Currently, we only allow a single token network per token and the one registering the network can set some settings at that time. This brings the risk of having bad settings for a token network without a way of changing the settings or using a different token network for that token.

Potential solutions:
* Don't allow any settings (chosen solution)
* Limit set of potential registrars to people choosing good values
* Allow multiple networks per token

Available settings:
* channel_participant_deposit_limit
* token_network_deposit_limit
* settlement_timeout_min (currently fixed to value set in registry)
* settlement_timeout_max (currently fixed to value set in registry)
* deprecation_executor (currently fixed to value set in registry)

If we removed the deposit limits and kept the other values fixed to the one in the registry, no settings would be left when registering a token network. This would allow us to go with the solution "Don't allow any settings".

@GataKamsky @czepluch

**Comment by czepluch** [comment]
Yeah, the deposits is another thing to think about, but I assume they will also be removed at some point.

**Comment by palango** [comment]
@GataKamsky I agree with Karl in that removing the limits and using fixed settings from the registry would be the easiest way to accomplish this. It would also reduce the code size and potentially help with issues related to that issue.

What do we need to push this forward?

**Comment by palango** [comment]
We'll not do this at this point in time. More infos in https://github.com/raiden-network/team/issues/924

**Comment by GataKamsky** [comment]
I agree with the proposal made by @karlb.
