### ISSUE TITLE
Using web3.js to sign the message 

### ISSUE THREAD

**Issue by BrianPHChen** [raiden-network/raiden-contracts#1417]
Hi, I'm trying to use web3.js to implement raiden network contracts.
However, there is an issue.
When the process runs recoverAddressFromWithdrawMessage() through setTotalWithdraw(), errors happened.

I traced the code and I can make sure the hash I signed is the same as the message_hash computed from `keccak256(abi.encodePacked(...))` of the smart contract.

But when I used [web3.eth.sign()](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#sign) to sign the hash, which can't recover the signer's address.
Then I checked the ECVerify.sol, I found that it does not have a prefix message in `ecverify(bytes32 hash, bytes memory signature)`.(https://ethereum.stackexchange.com/questions/19582/does-ecrecover-in-solidity-expects-the-x19ethereum-signed-message-n-prefix)
Is it because the original Raiden API is developed by Python so it is unnecessary or what?

Thanks

**Comment by BrianPHChen** [comment]
It turns out that I should use [`web3.eth.accounts.sign()`](https://web3js.readthedocs.io/en/v1.3.0/web3-eth-accounts.html#sign) to wrap the message up. Please closed the issue.
Thanks

**Comment by palango** [comment]
@BrianPHChen Great that you found a solution. Let us know when you run into any other problems!

**Comment by BrianPHChen** [comment]
Although I can correctly wrap the message, I still can't get the correct signer address. Have you tried web3js before?
