### ISSUE TITLE
Resolve unlock tests from raiden/test_withdraw.py

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-contracts#144]
Go over old [raiden/test_withdraw](https://github.com/raiden-network/raiden/blob/991275c9e8e9e4a4ccfdccb3a66a9e20950dd9b5/raiden/tests/smart_contracts/netting_channel/test_withdraw.py)  and rebuild the testing in `raiden-contracts `.  Be aware: `nettingchannel.withdraw` corresponds to `token_network.unlock` with the current protocol. I.e. the currently available tests in raiden-contracts are found [here](https://github.com/raiden-network/raiden-contracts/blob/d0be6f5ccc4be6498db85c182d24b4e3a5b8f681/raiden_contracts/tests/test_channel_unlock.py#L15):  

- [x] decide which tests to rewrite
- [x] adapt tests to new functionality with `withdraw <-> unlock`

**Comment by err508** [comment]
sub #92

**Comment by err508** [comment]
- [ ] [test_withdraw](https://github.com/raiden-network/raiden/blob/991275c9e8e9e4a4ccfdccb3a66a9e20950dd9b5/raiden/tests/smart_contracts/netting_channel/test_withdraw.py#L32) -> [test_channel_unlock](https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_unlock.py#L270)

**Comment by loredanacirstea** [comment]
@err508 , 

`test_withdraw_at_settlement_block` is not valid anymore in itself. The `unlock` (former `withdraw`) is completely different now. It batches the locks and you can only unlock them after `settleChannel` is called. The old test wanted to make sure that you could unlock individual locks during the settlement window, including the first block when `settleChannel` could have been called.

So the test that might makes sense here is: testing that you cannot call `unlock` before the channel is settled. 

`test_withdraw_expired_lock` - in the batched locks, we can have both expired & valid locks. We have tests that provide both expired & valid locks and then check if the resulting token balances are correct. E.g.
https://github.com/raiden-network/raiden-contracts/blob/a3886de67ec8a53caa3813aaee1d32bd26473175/raiden_contracts/tests/test_channel_unlock.py#L301
https://github.com/raiden-network/raiden-contracts/blob/a3886de67ec8a53caa3813aaee1d32bd26473175/raiden_contracts/tests/test_channel_unlock.py#L347-L349

So you can check these out if you want to add additional unit tests.

`test_withdraw_both_participants` - we need a test in which both participants have pending transfers and provide valid `locksroot`s in the balance proofs. We need to make sure that both can unlock the tokens contained in those transfers if they are valid.

`test_withdraw_twice` - for the current `unlock`, this remains true. A participant must not be able to `unlock` a second time.

`test_withdraw_fails_with_partial_merkle_proof` - This can be replaced with a test providing a smaller number of packed locks (`merkle_tree_leaves`) than what was used to compute the balance proof `locksroot`.

`test_withdraw_tampered_merkle_proof` - This can be replaced with a test providing invalid data for the `merkle_tree_leaves` (wrong length, wrong types for the packed data etc.)

`test_withdraw_lock_with_a_large_expiration` - we can keep this test and mock some locks with big expiration values

**Comment by err508** [comment]
> So the test that might makes sense here is: testing that you cannot call unlock before the channel is settled.

@loredanacirstea This happens with #154 [here](https://github.com/err508/raiden-contracts/blob/d73e97824a644dd9ce351fd4ec00dedeb1490f7c/raiden_contracts/tests/test_channel_unlock.py#L454)

> test_withdraw_expired_lock - in the batched locks, we can have both expired & valid locks. 

I added a [test](https://github.com/err508/raiden-contracts/blob/d73e97824a644dd9ce351fd4ec00dedeb1490f7c/raiden_contracts/tests/test_channel_unlock.py#L543) for unlocking with expired locks - it is currently not throwing as expected. I currently investigate why.

**Comment by err508** [comment]
> It should not throw. Unlock sends the valid (not expired) locked amounts to the participant who wants to unlock. And sends the rest of the tokens (from expired locks) back to the other participant, who initially sent this pending transfer.

Ok, so unlock will never fail, i.e. no way or reason to reproduce the behaviour of `test_withdraw_expired_lock`?

**Comment by loredanacirstea** [comment]
> Ok, so unlock will never fail, i.e. no way or reason to reproduce the behaviour of test_withdraw_expired_lock?

Exactly.

**Comment by err508** [comment]
Ok thx for elaborating. [This one ](https://github.com/err508/raiden-contracts/blob/d73e97824a644dd9ce351fd4ec00dedeb1490f7c/raiden_contracts/tests/test_channel_unlock.py#L573) still does't make to much sense to me, as the changed lock expiration does not make any difference when it comes to the transferred values.

**Comment by loredanacirstea** [comment]
>  This one still does't make to much sense to me, as the changed lock expiration does not make any difference when it comes to the transferred values.

In that specific case, we have `[1, 3, 5]` - mocked pending transfers with valid locks (secrets registered within the expiration time frame) and `[2, 4]` - mocked pending transfers with secrets that will not been registered in time. This is what `get_pending_transfers_tree` expects, in order to provide input data for `merkle_tree_leaves`.
`get_pending_transfers_tree` assigns some random `expiration` values based on the `min` & `max` values https://github.com/raiden-network/raiden-contracts/blob/a3886de67ec8a53caa3813aaee1d32bd26473175/raiden_contracts/tests/utils.py#L80

 In the linked test, the expirations are between `settle_timeout - 15` and `settle_timeout - 10`, so we have enough time to reveal the secrets. We then reveal the secrets for the mocked `[1, 3, 5]` transfers (`pending_transfers_tree.unlockable`). 

So, at this point `A` should be able to get the `1 + 3 + 5` tokens and B will get back the `2 + 4` tokens. `[2, 4]` are considered expired, because we don't reveal the secret on-chain (on purpose). 
This is the correct behavior that needs to be tested, and it is here: https://github.com/err508/raiden-contracts/blob/d73e97824a644dd9ce351fd4ec00dedeb1490f7c/raiden_contracts/tests/test_channel_unlock.py#L615-L616

However, as mentioned above, you can say that this case is already covered by other tests.

Not sure if this answers your question.

**Comment by err508** [comment]
Thx a lot, that answered the question just fine. I thought of the experitation in terms of the settle_timeout and not of the register secret. I'd say the withdraw_expired_lock case corresponds to the case where register_secret_time >= expiration, correct? Asking to map out the legacy testing correctly.

**Comment by loredanacirstea** [comment]
> the withdraw_expired_lock case corresponds to the case where register_secret_time >= expiration

Correct.
