### ISSUE TITLE
Resolve channel_close tests from raiden/test_close.py

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-contracts#145]
Go over old [raiden/[...]/test_close](https://github.com/raiden-network/raiden/blob/991275c9e8e9e4a4ccfdccb3a66a9e20950dd9b5/raiden/tests/smart_contracts/netting_channel/test_close.py) and rebuild the tests that that are missing [raiden-contracts/[...]/test_channel_close](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/tests/test_channel_close.py). 
- [x]     decide which tests to rewrite
- [ ]     rewrite them

**Comment by err508** [comment]
sub #92

**Comment by loredanacirstea** [comment]
`test_close_event ` - we have this here https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_close.py#L257

`test_close_first_participant_can_close ` - must be added

`test_close_second_participant_can_close` - must be added

`test_close_only_participant_can_close` - covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_close.py#L141

`test_close_first_argument_is_for_partner_transfer` - must be added; testing if that the transaction fails if the provided balance proof is from the same participant who closes

`test_close_accepts_only_transfer_from_participants` - should be covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_close.py#L83

`test_close_called_multiple_times` - covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_close.py#L113 - you can add the state check if you want

`test_close_wrong_channel`, `test_close_valid_tranfer_different_token` , `test_close_tampered_identifier`, `test_close_tampered_nonce`- replaced with tests that make sure `closeChannel` fails for balance proofs signed with an invalid/different `channel_identifier`, `token_network_address` , `chain_id`, `nonce` `balance_hash`, `additional_hash` than the one provided as an argument
