### ISSUE TITLE
 Resolve channel_deposit tests from raiden/[...]/test_deposit

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-contracts#146]
Go over old [raiden/[...]/test_deposit](https://github.com/raiden-network/raiden/blob/991275c9e8e9e4a4ccfdccb3a66a9e20950dd9b5/raiden/tests/smart_contracts/netting_channel/test_deposit.py) and rebuild the tests that that are missing [raiden-contracts/[...]/test_channel_close](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/tests/test_channel_deposit.py). 
- [ ]     decide which tests to rewrite
- [ ]     rewrite them

**Comment by err508** [comment]
sub #92

**Comment by loredanacirstea** [comment]
`test_deposit` - we have multiple tests covering these cases. Note that `cannot deposit without approving` - this is out of the scope of `deposit`. It is in the scope of the token and it might be different for each token standard (e.g. ERC223 does not need approving). I don't think this should be a test case for `deposit`.

`test_deposit_events` - partially covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_deposit.py#L173 . For the `Transfer` event, we might need changes to our `LogHandler` , not sure if it currently picks up the `Transfer` from the same transaction hash.

**Comment by err508** [comment]
@loredanacirstea IMO we can close this one, deposit coverage is increased a lot already. Agreed?

**Comment by loredanacirstea** [comment]
@err508 , yes. I agree.
