### ISSUE TITLE
Allow update channel state anytime before a channel is settled

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-contracts#1461]
This is explicitly forbidden and an explanation is given:

https://github.com/raiden-network/raiden-contracts/blob/bc63012b77ced282b61c1b9f74baa107579c308e/raiden_contracts/data/source/raiden/TokenNetwork.sol#L612-L632

But I am not convinced that this is a good decision, as this behavior can cause update failures when the blockchain is congested. I lean towards allowing channel updates whenever possible.

**Comment by konradkonrad** [comment]
+1 on removing this check.

There can be several reasons (actual congestion, too high gas prices compared to expected reward) why a channel will not be settled, or the balance will not be updated, ASAP.

As long as it is not settled, the partner should be allowed to update their balance.

The race condition mentioned in the comment exists, but for both sides. For the case of the `settle` call failing, it can easily be found out during `post-failed-tx` check, that the balance hashes have changed. The client can the restart the `settle` call with the updated parameters.
