### ISSUE TITLE
Resolve channel_settle tests from raiden/[...]/test_settle 

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-contracts#147]
Go over old [raiden/[...]/test_settle](https://github.com/raiden-network/raiden/blob/991275c9e8e9e4a4ccfdccb3a66a9e20950dd9b5/raiden/tests/smart_contracts/netting_channel/test_settle.py) and rebuild the tests that that are missing [raiden-contracts/[...]/test_channel_settle](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/tests/test_channel_settle.py). 
- [x]     decide which tests to rewrite
- [x]     rewrite them

**Comment by err508** [comment]
sub #92

**Comment by loredanacirstea** [comment]
`test_settle_event` - covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_settle.py#L196

`test_settle_unused_channel` - covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_settle.py#L26

`test_settle_single_direct_transfer_for_closing_party` - must be added

`test_settle_single_direct_transfer_for_counterparty` - must be added

`test_settle_two_direct_transfers` - covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_settle.py#L69 , but if you want to also write a simple test, that's fine.

`test_settle_with_locked_mediated_transfer_for_counterparty` - a simple test for this can be added
`test_settle_with_locked_mediated_transfer_for_closing_party` - same
`test_settle_two_locked_mediated_transfer_messages` - same

`test_two_direct_transfers`, `test_mediated_after_direct_transfer` - these are more Raiden client test than a contracts test, so no need to be added

`test_settlement_with_unauthorized_token_transfer` - can be replicated by sending some tokens `extra_amount` to the `TokenNetwork` contract, creating a channel and settling it, making sure that `extra_amount` stays in the contract.

`test_netting` - can be covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_channel_settle.py#L69, we just have to make sure that the case is added to `channel_settle_test_values`

**Comment by err508** [comment]
@loredanacirstea `test_settle_with_locked_mediated_transfer_for_counterparty [...]` is IMO covered by `test_channel_settle_and_unlock` - from contracts perspective there is no diff between a mediated and direct transfer.

**Comment by loredanacirstea** [comment]
For the sake of documenting this:
`test_settle_with_locked_mediated_transfer_for_counterparty` is testing that if we make a mediated transfer and send the balance proof before the mediated transfer finalizes (e.g. see `BP_I_1` from `Mediated Transfer - Best Case Scenario` http://raiden-network-specification.readthedocs.io/en/latest/messaging.html#id16 ) and the lock is not unlocked on-chain (old `withdraw` function), then the lock/trransfer amount is not deducted from the payer.

So, to cover it, we need:
- a balance proof with 1 pending lock for the non-closing party
- NOT reveal the secret on chain for this lock
- close & settle the channel with this balance proof
- check the participant balances `settle_state_tests`
- call `unlock` - at this point, the final participant balances should be as if that transfer did not happen.
