### ISSUE TITLE
Resolve channel_update_transfer tests from raiden/[...]/test_updatetransfer

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-contracts#148]
Go over old [raiden/[...]/test_updatetransfer](https://github.com/raiden-network/raiden/blob/991275c9e8e9e4a4ccfdccb3a66a9e20950dd9b5/raiden/tests/smart_contracts/netting_channel/test_updatetransfer.py) and rebuild the tests that that are missing [raiden-contracts/[...]/test_update_transfer](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/tests/test_channel_update_transfer.py). 
- [x]     decide which tests to rewrite
- [x]     rewrite them

**Comment by err508** [comment]
sub #92

**Comment by err508** [comment]
@loredanacirstea talking `test_update_not_allowed_for_the_closing_address` - `updateNonClosingBalanceProof`can be called by anyone. I'll reinterpret that to a test, where someone tries to call it with a balance proof signed by the closer.

**Comment by loredanacirstea** [comment]
For the sake of documentation:
`test_update_not_allowed_for_the_closing_address` tests that the closing party cannot:
1. update **his own** balance proof through the old `updateTransfer` function
2. update **his partner's** balance proof through the old `updateTransfer` function

For the current state of the contracts, regarding `updateNonClosingBalanceProof` (revamped `updateTransfer`):
1. must **not** be allowed
2. is allowed.

So:

> I'll reinterpret that to a test, where someone tries to call it with a balance proof signed by the closer

I agree.
