### ISSUE TITLE
Add function to remove limits after deployment

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-contracts#1481]
We would like to lift the current limits on TokenNetworks, but we won't be able to do that at the time of the next mainnet deployment. This could be solved by introducing a function that removes the limits and can only be called by the contract owner (like the deprecation switch). In addition, we would like to be able to transfer contract ownership to new address.

Requires https://github.com/raiden-network/raiden-contracts/issues/1416.

- [x] Find a good name for the contract owner. Since the owner can only deprecate, change the owner and lift the limits, using the term ownership seems misleading.
- [x] Add a removeLimits function to TokenNetworkRegistry. Can only be called by owner and sets `max_token_networks` to maxint.
- [x] Add a removeLimits function to TokenNetwork. Can only be called by owner and sets `channel_participant_deposit_limit` and `token_network_deposit_limit` to maxint.
- [x] Change variable name `deprecation_executor` to `owner` (or whatever has been decided as name)
- [x] Add a changeOwner function to TokenNetworkRegistry. Can only be called by owner and sets the owner to the address given as a parameter.
- [x] Add a changeOwner function to TokenNetwork. Can only be called by owner and sets the owner to the address given as a parameter.

**Comment by istankovic** [comment]
> Find a good name for the contract owner. Since the owner can only deprecate, change the owner and lift the limits, using the term ownership seems misleading.

Contract... operator? Administrator? Controller? Custodian? Governor?

**Comment by karlb** [comment]
> Contract... operator? Administrator? Controller? Custodian? Governor?

I like "controller" best. Let's go with that one.
