### ISSUE TITLE
Resolve test_registry tests from raiden/[...]/test_registry

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-contracts#151]
Go over old [raiden/[...]/test_registry](https://github.com/raiden-network/raiden/blob/991275c9e8e9e4a4ccfdccb3a66a9e20950dd9b5/raiden/tests/smart_contracts/test_registry.py) and rebuild the tests that that are missing.  sub #92 

- [x]  assess if tests have to be rebuild
- [x] if yes, rebuild them

**Comment by loredanacirstea** [comment]
`test_registry` - some of it should have been covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_token_network_registry.py#L94, but it seems I messed up the test, so it must be fixed to actually test `token_to_token_networks` and not `secret_registry_address` & `chain_id`
- add a separate test for calling `createERC20TokenNetwork` twice with the same token -> should fail
- event test is already covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_token_network_registry.py#L112


`test_registry_reject_empty_address` - covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_token_network_registry.py#L62

`test_registry_nonexistent_token` - covered by https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_token_network_registry.py#L62

`test_all_contracts_same_version` - covered by multiple tests:
https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_token_network_registry.py#L13-L15
https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_token_network.py#L6-L7
https://github.com/raiden-network/raiden-contracts/blob/d6e7f6d08ff3a0c723b83600cae851bb479d137d/raiden_contracts/tests/test_secret_registry.py#L9-L11
