### ISSUE TITLE
Add functions to change limitations gradually

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-contracts#1566]
Currently the contracts are deployed with limits. Those limits can later be removed, but not changed gradually.

Instead of removing the limits completely, we can add a way to change them.

- `TokenNetworkRegistry.removeLimits()` could be changed to `TokenNetworkRegistry.increaseLimits(new_limit)`, which increases the limit of token networks to the absolute value of `new_limit`.
- `TokenNetwork.removeLimits()` could be changed to `TokenNetwork.increaseLimits(new_channel_participant_deposit_limit, new_token_network_deposit_limit)`, which would increase those limits.

Both should check, that the values can only increase, not decrease.

@DinaBB

**Comment by taleldayekh** [comment]
@netcriptus sync with @karlb on Thursday about this.

**Comment by taleldayekh** [comment]
We won't be implementing this due to not being in scope and it is more a nice to have rather than a must.
