### ISSUE TITLE
Analysis of the settlement algorithm & attack vectors

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#188]
I have analyzed some edge cases that could have made attacks possible and demonstrated that there cannot be attacks in those specific cases (until proven wrong).

I cannot guarantee that all edge cases have been analyzed. The logic & calculations presented in my 6 comments below should also be verified by others.

TODO:
I have started by analyzing the current settlement algorithm. It would be worth to also analyze the edge cases irrespective of the current implementation, as mentioned in https://github.com/raiden-network/raiden-contracts/issues/188#issuecomment-405214043 and https://github.com/raiden-network/raiden-contracts/issues/188#issuecomment-407406686

**Comment by loredanacirstea** [comment]
# Settlement algorithm

## Definitions:

- `valid last BP` = a balance proof that respects the official Raiden client constraints and is the last balance proof known.
- `valid old BP` = a balance proof that respects the official Raiden client constraints, but there are other newer balance proofs that were created after it (additional transfers happened)
- `invalid BP` = a balance proof that does not respect the official Raiden client constraints; E.g. someone else implements a malicious Raiden client and convinces people to use it.

```
Channel participants: P1, P2
D1 = P1's deposit
W1 = P1's withdrawn amount
T1 = P1's transferred amount to P2
L1 = P1's locked amount in pending transfers to P2
Lc1 = P1's locked amount in pending transfers to P2, that can be claimed by P2 (locks secrets have been registered on-chain, in the Secret Registry)
Lu1 = P1's locked amount in pending transfers to P2, that is unclaimable by P2 (locks secrets have not been registered on-chain), therefore belongs to P1
L1 = Lc1 + Lu1

TAD = total available deposit

B1 = total final amount that must be received by P1 after channel settlement and unlock
S1 = amount received by P1 at settlement
SL1 = amount locked in the TokenNetwork contract at settlement time, representing L1
B1 = S1 + SL1

AB1 = available balance for P1; determines if P1 can make additional transfers to P2 or not
```

## Constraints
```
(1) TAD = D1 + D2 - W1 - W2 ; TAD >= 0
(2) B1 = D1 - W1 + T2 - T1 + Lc2 - Lc1
(3) B2 = D2 - W2 + T1 - T2 + Lc1 - Lc2
(4) B1 + B2 = TAD
```

## Constraints that must be enforced by the Raiden client
```
(5) AB1 = D1 - W1 + T2 - T1 - L1; AB1 >= 0
(6) W1 <= D1 + T2 - T1 - L1
(7) T1 + L1 < 2^256 ; T2 + L2 < 2^256
```

## Settlement algorithm, as used now:
https://github.com/raiden-network/raiden-contracts/blob/4dc3b55f9bb8c86111f63bae273a08025a675789/raiden_contracts/contracts/TokenNetwork.sol#L598

```
RmaxP1 = maximum amount that can be received by P1 after channel is settled and unlock was called
RmaxP2 = maximum amount that can be received by P2 after channel is settled and unlock was called
```

```
# Underflows are solved by enforcing T2 + L2 > T1 + L1 when calling settleChannel & by (6)
# Overflows are solved by (7)
RmaxP1 = (T2 + L2) - (T1 + L1) + D1 - W1

# We need to bound this by TAD, so participants don't steal tokens from other channels when using old balance proofs
RmaxP1 = max(TAD, RmaxP1)

# We need to bound the locked amount that remains in the contract, in case old balance proofs with a high L2 is used
SL2 = max(RmaxP1, L2)
S1 = RmaxP1 - SL2

# Underflow solved by the above bounding of RmaxP1
RmaxP2 = TAD - RmaxP1

# We need to bound the locked amount that remains in the contract, in case old balance proofs with a high L1 is used
SL1 = max(RmaxP2, L1)
S2 = RmaxP2 - SL1
```

`settleChannel` must not fail and it was constructed to handle overflows and underflows without failing. Some explanations here: https://github.com/raiden-network/raiden-contracts/issues/117#issuecomment-395780012

Due to bounding the values there are some points where attacks might be possible:

```
RmaxP1 = max(TAD, RmaxP1)
```

```
SL2 = max(RmaxP1, L2)
```

For reference, more explanations on the process of arriving to this settlement algorithm:
https://github.com/raiden-network/raiden-contracts/pull/131
https://github.com/raiden-network/raiden-contracts/pull/123

For reference, the old implementation of the settlement algorithm:
https://github.com/raiden-network/raiden/blob/80b0ccaae62aa1ca109cd04101fc51f6eaac8cfc/raiden/smart_contracts/NettingChannelLibrary.sol#L309-L341

**Comment by loredanacirstea** [comment]
# Attack vectors

[1]
```
SL2 = min(RmaxP1, L2)
```
An attack might be possible if `RmaxP1 < L2`, because we exclude `L2 - RmaxP1` tokens from the calculation. 

**Cases:**
a) `valid last BP P1` & `valid last BP P2`
b) `valid last BP P1` & `valid old BP P2` with a high `L2`, that needs bounding to `TAD`
c) `valid old BP P1` & `valid old BP P2`
d) at least 1 `invalid BP` - this case implies both P1 and P2 are using an unofficial, malicious Raiden client. The TokenNetwork smart contract has no way to determine the correct final amounts. Therefore, there are no guarantees about the channel settlement amounts.

## Case a):
```
RmaxP1 = AB1 + L2
AB1 >= 0

=> RmaxP1 >= L2
```
No attack, as long as AB1 is enforced by the Raiden client.

## Case b):
Discovered while working on https://github.com/raiden-network/raiden-contracts/issues/132

Note: The attack vector described here was also present in the old settlement algorithm https://github.com/raiden-network/raiden/blob/80b0ccaae62aa1ca109cd04101fc51f6eaac8cfc/raiden/smart_contracts/NettingChannelLibrary.sol#L309. 
The attacker would have received all the claimable locks by unlocking them before settlement.

Old balance proofs at `time=t_k`:
```
D1k = 35
W1k = 5
T1k = 20006
Lc1k = 0
Lu1k = 0

D2k = 40
W2k = 10
T2k = 19987
Lc2k = 49
Lu2k = 0
```

Last known balance proofs at `time=t`:
```
D1 = 35
W1 = 5
T1 = 20020
Lc1 = 3
Lu1 = 1

D2 = 40
W2 = 10
T2 = 20030
Lc2 = 4
Lu2 = 2
```
P1 = attacker, uses P2's old balance proof at time `t_k`.

- we check if the balance proofs were valid:
```
AB1k = D1k - W1k + T2k - T1k - L1k = 35 - 5 + 19987 - 20006 - 0 = 11 >= 0
AB2k = D2k - W2k + T1k - T2k - L2k = 40 - 10 + 20006 - 19987 - 49 = 0 >= 0

AB1 = D1 - W1 + T2 - T1 - L1 = 35 - 5 + 20030 - 20020 - 4 = 36 >= 0
AB2 = D2 - W2 + T1 - T2 - L2 = 40 - 10 + 20020 - 20030 - 6 = 16 >= 0
```

- we calculate how many token should P1 and P2 receive in total if they use the last balance proofs:
```
P1 = D1 - W1 + T2 - T1 + Lc2 - Lc1 = 35 - 5 + 20030 - 20020 + 4 - 3 = 41
P2 = D2 - W2 + T1 - T2 + Lc1 - Lc2 = 40 - 10 + 20020 - 20030 + 3 - 4 = 19
41 + 19 = 60 = TAD
```

- we calculate how many tokens will P1 and P2 receive if BP_P1 & BP_P2k are used:
```
RmaxP1 = (T2k + L2k) - (T1 + L1) + D1 - W1 = 19987 + 49 - 20020 - 4 + 35 - 5 = 42

SL2 = min(RmaxP1, L2) = min(42, 49) = 42
S1 = 0

RmaxP2 = 18
SL1 = 4
S1 = 14
```
- after settlement, in the `unlock` phase, the current algorithm first calculated the `claimable` amount and transfers it. This means that P1 will receive the `42` tokens instead of `41`.
This results in `P1` stealing 1 token. It is possible to construct examples where more tokens are stolen.

**Comment by loredanacirstea** [comment]
# Attack vectors

(work in progress)

[2]

```
RmaxP1 = min(TAD, RmaxP1)
```

**Comment by loredanacirstea** [comment]
# Mitigation

(work in progress)

At a first glance, we might be able to mitigate the attack described at [1] b).
We know that a `valid old` balance proof was used, because `RmaxP1 < L2` only happens in this case. Therefore, it is a matter of finding out/deciding what is the correct thing to do at this point.

**Comment by loredanacirstea** [comment]
# Mitigation

(work in progress)

At a first glance, we might be able to mitigate the attack described at [1] b).
We know that a `valid old` balance proof was used, because `RmaxP1 < L2` only happens in this case. Therefore, it is a matter of finding out/deciding what is the correct thing to do at this point.

We can also consider forcing participants to call `unlock` in the settlement window. Participants must provide the `balance_hash` data + pending transfers merkle tree data, we store the `claimable` & `unclaimable` amounts and compute everything when calling `settleChannel`. Maybe even do this in the same transaction.

**Comment by loredanacirstea** [comment]
# Mitigation

(work in progress)

## Mitigation ideas for [2]a)
https://github.com/raiden-network/raiden-contracts/issues/188#issuecomment-404844699

- We see that `L2 > RmaxP1` only happens for an old/invalid balance proof of B, sent by A. Therefore, we can consider punishing A by setting `RmaxP1 = 0` and sending the rest of the tokens to B. `L2 > RmaxP1` does not happen for all old balance proofs, only for particular balance proofs that follow the constraints explained in the [2]a) case. Therefore, this punishment is fair as long as A is alerted about the amount he will receive, in case he wants to change the balance proof. This approach is similar to what happens for [1]
  - we can add `view` functions in the `TokenNetwork` contract to be able to query how big is the computable amount, to alert users if the result is `0` - maybe they decide to use another balance proof.

- An idea that might seem good is doing the two `unlock` before or in the same transaction as `settleChannel`.
  - if we `unlock` before the settlement calculations, A can steal even more tokens, because he can use a balance proof with a bigger `Lc2k` than [2]a) actually permits to be stolen.
  - if we ` 2 * unlock` + `settleChannel`, even though we have all the values and we can compute the final balances, for [2]a)i) we would still get `B1 = 52, B2 = 8` (4), (5) and we would still have to deal with the decision of who to punish or not.

**Comment by hackaugusto** [comment]
### Settlement algorithm
#### Constraints
`(7) Lck <= Lct, k < t` is not correct. example:

1. A opens a channel with B, deposits 10
2. A sends a mediated transfer to B with lock.amount equal to 3 (Ta=0, Lca=0, Lua=3)
3. B requests the secret, and A sends the secret reveal (Ta=0, Lca=3, Lua=0)
4. A sends the unlock to B (Ta=3, Lca=0, Lua=0)

For k=3 and t =4 we have Lca3=3 Lca4=0, the correct constraint is `(5R) T1k + Lc1k <= T1t + Lc1t, k < t`

**Comment by loredanacirstea** [comment]
In my opinion we can close this issue. 
The specs have been improved (https://github.com/raiden-network/spec/issues/110), to explain the settlement algorithm and my above proofs have not been disproved after the internal audit.

@LefterisJP, @hackaugusto can we close this?

**Comment by LefterisJP** [comment]
Well as far as an internal analysis is concerned I would say yes we can close this issue.
