### ISSUE TITLE
Use channel_identifier instead of the participant addresses pairs in the channel functions

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#193]
# Issues

As pointed out by @hackaugusto , the channel lifecycle is unclear, the `TokenNetwork` contract does not have a consistent interface for determining a channel's state.

One problem is that the two participants can reopen the channel after it was settled. The channel will have a different `channel_identifier` than the previous one. If this is not clear in the smart contract function calls and events, it introduces issues in the Raiden client, because the channel lifecycle is hard to track down in a clear & easy way.

(**update**: the following is not solved by neither proposed solutions from this description. It is solved by either refactoring data structures or ABI consistency : https://github.com/raiden-network/raiden-contracts/issues/201). Currently there is a lot of confusion when calling functions because we need to provide both participants, but usually one of the participants also has a role and the caller needs to pay attention at the participant addresses order. This has brought even myself a lot of pain when testing.

Another problem, as mentioned in https://github.com/raiden-network/raiden-contracts/pull/39#discussion_r183750230, the channel lifecycle is not clear also due to the `unlock` data that remains in the contract after the `settleChannel` transaction, while the channel data is removed.

## Current implementation 

Now we use the `participant`, `partner` addresses for determining a channel in the `TokenNetwork` functions and the `ChannelUnlocked` event (all events except `ChannelUnlocked` have the `channel_identifier` as an argument).
E.g.
```
function setTotalDeposit(address participant, uint256 total_deposit, address partner)

event ChannelUnlocked(
        address indexed participant,
        address indexed partner,
        bytes32 indexed locksroot,
        uint256 unlocked_amount,
        uint256 returned_tokens
    );
```
Current `channel_identifier` is defined as `channel_identifier = keccak256(keccak256(participant1, participant2), channel_counter)`, where `participant1, participant2` are in lexicographic order.

We currently have three getters for the channel state, which is confusing for getting the actual state from older channels that still have `unlock` data on chain. You can't actually check if a channel corresponding to a `channel_identifier` has an `unlock` to do or not.
```
# returns channel_identifier, settle_block_number, state (1 = open, 2 = closed, 0 = non-existent or settled)
function getChannelInfo(address participant1, address participant2)

# returns deposit, withdrawn_amount, is_the_closer, balance_hash, nonce
function getChannelParticipantInfo(address participant, address partner)

# returns locked_amount
function getParticipantLockedAmount(address participant1, address participant2, bytes32 locksroot)
```

This is because we have a separate mapping for the locked amounts:
```
# The key is `keccak256(participants_hash + participant_address + locksroot)`
# The value is the total amount of tokens locked in the pending transfers corresponding to
# the `locksroot`, that were sent by `participant_address` to his channel partner.
mapping(bytes32 => uint256) locksroot_identifier_to_locked_amount;
```

## Previous refactorings 

For documentation, we had multiple refactorings regarding this:
- we decided to allow multiple channels per 2 participants in the February team retreat. Issue: https://github.com/raiden-network/raiden-contracts/issues/1 that links the first commit from `raiden-contracts` to the initial `raiden` repo smart contracts refactoring & discussions that took place here https://github.com/raiden-network/raiden/pull/1286.
  - we used a global, monotonically increasing `uint256` channel counter
- limiting the number of channels between two participants at only `1` at the same time: spec issue https://github.com/raiden-network/spec/issues/55, repo issue https://github.com/raiden-network/raiden-contracts/issues/40, fix: https://github.com/raiden-network/raiden-contracts/pull/58
  - we switched to participant address pairs (old implementation from `raiden` initial contracts); at that point in time the counter was not used because I did not see the replay attack issue and did not have the idea that limiting the number of channels can be solved just by doing an additional SSTORE for the counter, linked to the participant addresses hash.
- replay attack triggered by previous refactoring: issue - https://github.com/raiden-network/raiden-contracts/issues/141, fix - https://github.com/raiden-network/raiden-contracts/pull/170
  - solved by adding the global channel counter to the `channel_identifier`, along with the participant addresses.

## Proposed solution:

As @hackaugusto proposed, the architecture for both smart contracts and Raiden client can be constructed in a more extensible way around the `channel_identifier`, as opposed to the participant addresses pair.
For the `TokenNetwork` contract this means all function calls & events must use the `channel_identifier`.

As proposed by @palango  in https://github.com/raiden-network/raiden-contracts/issues/193#issuecomment-407146028, `bytes32 channel_identifier` can be replaced with `uint256 channel_identifier` == the global channel counter + keeping `mapping (bytes32 => uint256) public participants_hash_to_channel_counter;`

I think a consistent way to get the channel state can therefore be achieved with:

- Function calls having the following form:
```
function setTotalDeposit(uint256 channel_identifier, uint256 total_deposit, address participant)
```

- Channel info getters:
```
# returns the `uint256 channel_identifier` (channel counter) if the channel exists or 0 otherwise
function getChannelIdentifier(address participant, address partner)

# returns settle_block_number, state (0 = non-existent, 1 = open, 2 = closed, 3 = settled_but_pending_unlock)
function getChannelInfo(uint256 channel_identifier)

# returns deposit, withdrawn_amount, is_the_closer, balance_hash, nonce, lockhash_locked_amount
function getChannelParticipantInfo(uint256 channel_identifier, address participant)
```

- storing the `unlock` data in a way that allows checking if a channel corresponding to a `channel_identifier` is pending an `unlock` or not. We can get the actual `locked_amount` in the contract for a certain `locksroot` from the `ChannelSettled` event. The following proposal does not cost more gas than the current implementation.
```
// The key is `keccak256(uint256 channel_identifier, address participant_address)`
// The value is `keccak256(bytes32 locksroot, uint256 locked_amount)` 
mapping(bytes32 => bytes32) unlock_identifier_to_lockhash_locked_amount;

function unlock(
        uint256 channel_identifier,
        address claiming_participant,
        address payer_participant,
        uint256 locked_amount,
        bytes merkle_tree_leaves
);

event ChannelSettled(
        uint256 indexed channel_identifier,
        uint256 participant1_amount,
        uint256 participant2_amount,
        uint256 locked1_amount,
        uint256 locked2_amount
    );

event ChannelUnlocked(
        uint256 indexed channel_identifier,
        bytes32 indexed locksroot,
        uint256 unlocked_amount,
        uint256 returned_tokens
    );
```

Note - there are 3 things in the above proposal, that can be implemented individually and are independent:
- make the `channel_identifier` a monotonic counter `uint256`
- use the `channel_identifier` in the `TokenNetwork` contract interface, replacing the pair of participant addresses
- allow the `unlock` data to be queried just by knowing the `channel_identifier` and the `participant` address, therefore allowing the smart contract to provide the correct channel state at any point in time.

**Comment by palango** [comment]
What do you imagine the `channel_identifier` to look like? Right now it's a hash, but with these change we could go back to an integer.

**Comment by loredanacirstea** [comment]
@palango , I think you are right. Updated the description with more info & a proposed solution. Used your idea about going back to the `uint256` channel counter.

**Comment by err508** [comment]
After talking to Augusto, here my understanding of the problem to be solved: 
If the client crashes and needs to recover by going through the state transitions in the WAL, there are currently no means to distinguish between different channel life cycles (i.e. `open -> close -> settle -> open` looks the same as `òpen->` ).

### Proposed solution

tl,dr: I counsel strongly against changing the contract functions signatures from `participant_1 participant_2` to `channel counter`. Instead I propose to make the global `channel_counter` callable via the `channel` struct in the contracts to solve the given problem. This would not require yet another re factoring of a critical part of the code base. We could instead simplify the contracts code by replacing `channel_identifier` with `channel_counter `, leave the rest of the code as it is. It might seem less structured to having only unique channels. However, we have the channel counter already to distinguish the same channel at different points in time. Making this more explicit adds complexity and decreases generality and expressiveness of our model. 

### How would that solve the problem? 
The client can access the `channel_counter` via `getChannelInfo` when recovering. The two life cycles `open_1 -> close -> settle -> open_2` and `òpen_1->` could be distinguished due to having different `channel_counters`  for  `open_1` and `open_2`. Outdated onchain transactions with a different `channel_counter` could simply be skipped. 

### Pros
- we leave most contract functions as they are, minimal changes to solve the given problem
- we keep the notion of a channel as concise as it is: We define a channel in the sense of a graph edge, i.e. two vertices/nodes make an edge/channel. We use this in the PFS, it is a model of a channel network where we can use **standard mathematical ideas from graph theory, please 
do not break that**.
- we solve the replay issue 
- we keep the ability to have out-of-order unlocks: currently `open -> close -> settle -> open -> close -> settle -> unlock -> unlock ` works right now, I don't see any reason to break that. 

### Cons

- api calls like `close/participant_1_address-participant_2_address` might be less intuitive 
- might seem less structured than thinking of channels as unique

**Comment by palango** [comment]
I see no issues from the PFS side, as we get our information from the events and the `channel_identifier` is in there as well as the participants.

> However, we have the channel counter already to distinguish the same channel at different points in time. Making this more explicit adds complexity and decreases generality and expressiveness of our model.

What do you mean with this? I feel like making naming different channels differently make the whole thing more expressive. Also the way to allowing multiple channels in the future would be easier, as we would only need to drop the mapping of partner_addresses to nonce, making it more general in my understanding.

**Comment by LefterisJP** [comment]
Rough documentation of the discussion we had in Berlin on 24/07 July:

- We will go with the 3 changes of the contracts as proposed by Loredana in the [first](https://github.com/raiden-network/raiden-contracts/issues/193#issue-343704868) post of this issue.
- We are going to make 3 changes in the client which will be documented at [1907](https://github.com/raiden-network/raiden/issues/1907) with each one having its own separate issues. Refer to that issue for more details.

**Comment by loredanacirstea** [comment]
Just a note, regarding the proposal for storing the `unlock` data: 
```
// The key is `keccak256(uint256 channel_identifier, address participant_address)`
// The value is `keccak256(bytes32 locksroot, uint256 locked_amount)` 
mapping(bytes32 => bytes32) unlock_identifier_to_lockhash_locked_amount;
```
This would mean the Raiden client needs to store the `locked_amount` from the `ChannelSettled` event and use it when calling `unlock`, in order to verify the `keccak256(locksroot, locked_amount)` stored in the contract.

I mostly opted for this due to reduced gas cost, but @hackaugusto proposed to use something more simpler.

So, an alternative would be:
```
struct UnlockData {
     bytes32 locksroot;
     uint256 locked_amount;
}

// The key is `keccak256(uint256 channel_identifier, address participant_address)`
mapping(bytes32 => UnlockData) public unlock_identifier_to_unlock_data;
```

Please confirm.

**Comment by LefterisJP** [comment]
> Please confirm.

I confirm. Please use the simpler approach as discussed in our meeting.

**Comment by loredanacirstea** [comment]
@err508 , Regarding https://github.com/raiden-network/raiden-contracts/issues/193#issuecomment-407328107:

I may have misunderstood your proposal as being the same one from https://github.com/raiden-network/raiden-contracts/issues/193#issuecomment-407146028

> Instead I propose to make the global `channel_counter` callable via the `channel` `struct` in the contracts to solve the given problem.
> The client can access the `channel_counter` via `getChannelInfo` when recovering

What do you mean by this? 
You want to add an additional storage slot to `struct Channel`, with the `channel_counter`?

> We could instead simplify the contracts code by replacing `channel_identifier` with `channel_counter`, leave the rest of the code as it is

`channel_identifier` will still be used as a term - this is something enforced by our agreed upon terminology https://github.com/raiden-network/spec/blob/master/terminology.rst.
So, do you mean replacing the current `bytes32` content of `channel_identifier` with the `uint256` value from the `channel_counter`, at the moment when the channel was created?

It is hard to understand your exact proposal without providing some pieces of code ..

**Comment by loredanacirstea** [comment]
Fixed through 
https://github.com/raiden-network/raiden-contracts/pull/195
https://github.com/raiden-network/raiden-contracts/pull/198
https://github.com/raiden-network/raiden-contracts/pull/203

For getting all the channel states through the same endpoint, https://github.com/raiden-network/raiden-contracts/issues/211 has been opened.
