### ISSUE TITLE
ABI conventions for function arguments

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#201]
Discussing function arguments convention after https://github.com/raiden-network/raiden-contracts/pull/198 is merged.

(As mentioned, until now, the contracts have been refactored numerous times, with the main focus on features rather than consistency. I consider this the phase where we should align on consistency & security.)

Scope: Make sure the interface is consistent and agreed upon. This minimizes confusion in the Raiden client or other clients that may be used.

## Predominant convention used now:
1. `channel_identifier`
2. participant address most important to the call, usually defined as `participant`
3. arguments that belong to 2.
4. other participant address, if necessary, usually defined as `partner`
5. arguments that belong to 4.
6. signatures, if necessary, in the participants order as seen above

## Functions that do not follow the above convention:
- `updateNonClosingBalanceProof` - 2. & 4. are reversed, as the most important address here is `non_closing_participant`
- `unlock` - 2. & 4. are reversed, as the most important address here is actually `partner` in my opinion, who sent the pending transfers. This is because these pending transfers will not necessarily go to `participant`.

## Additional Ideas:
- use more suggestive names, instead of `participant` and `partner`. E.g. `payer_participant`, `payee_participant` for `unlock`; `receiving_participant` for the `participant` receiving the deposit or similar.

## Questions: 
- is the above a good convention? what are other proposals?
- what function interface needs changing?

## Implementation:
```
function setTotalDeposit(
        uint256 channel_identifier,
        address participant,
        uint256 total_deposit,
        address partner
    )

function setTotalWithdraw(
        uint256 channel_identifier,
        address participant,
        uint256 total_withdraw,
        address partner,
        bytes participant_signature,
        bytes partner_signature
    )

function closeChannel(
        uint256 channel_identifier,
        address partner,
        bytes32 balance_hash,
        uint256 nonce,
        bytes32 additional_hash,
        bytes signature
    )

function updateNonClosingBalanceProof(
        uint256 channel_identifier,
        address closing_participant,
        address non_closing_participant,
        bytes32 balance_hash,
        uint256 nonce,
        bytes32 additional_hash,
        bytes closing_signature,
        bytes non_closing_signature
    )

function settleChannel(
        uint256 channel_identifier,
        address participant1,
        uint256 participant1_transferred_amount,
        uint256 participant1_locked_amount,
        bytes32 participant1_locksroot,
        address participant2,
        uint256 participant2_transferred_amount,
        uint256 participant2_locked_amount,
        bytes32 participant2_locksroot
    )

function unlock(
        uint256 channel_identifier,
        address participant,  # address who would receive the claimed locked tokens
        address partner,   # address who sent the pending transfers in the merkle tree
        bytes merkle_tree_leaves
    )

function cooperativeSettle(
        uint256 channel_identifier,
        address participant1_address,
        uint256 participant1_balance,
        address participant2_address,
        uint256 participant2_balance,
        bytes participant1_signature,
        bytes participant2_signature
    )
```

**Comment by pirapira** [comment]
I think I need to warn against changing the ordering of arguments at this point.  Even after swapping two `address`s, the function signature hash stays the same.  So, one has to be extremely careful when they have to deal with multiple versions of the TokenNetwork contract.

**Comment by loredanacirstea** [comment]
I agree. At this point it also makes little sense to change something that is working, with the risk of introducing bugs/attacks. We can revisit this if needed, later on. I will close this for now.
