### ISSUE TITLE
Use a proper signature standard

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#241]
Previous discussions:
https://github.com/raiden-network/spec/issues/23
https://github.com/raiden-network/spec/issues/67

This was also brought up by @berndbohmeier in the internal audit, where he suggested:
> So the dataformat I suggest talking about is
>
> `0x19 <1 byte version> <version specific data> <data to sign>` (eip 191)
> So in particular for raiden messages:
> `0x19 0x00 <token_network_address> <chain_id> <message_id> <message specific data to sign>`

## Issue

We do not use an official standard for signed messages. We just tightly pack the message data and sign it. Therefore, it is possible (though improbable and hard to reproduce) to have collisions with Ethereum transactions, other dapps, other Raiden messages, especially if we are not careful when constructing the messages. Therefore, messages signed by the Raiden client may be used for other purposes, as mentioned before, or messages signed through other means may be used for the Raiden Network.

## Possible solutions

Adopt one of the community's agreed upon standards:
  - https://github.com/ethereum/EIPs/blob/master/EIPS/eip-191.md
  - https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md

Another solution, for avoiding future collisions with other Raiden client messages is implementing unique message identifiers for each message, as proposed in https://github.com/raiden-network/spec/issues/67.

**Comment by loredanacirstea** [comment]
From internal discussions, https://github.com/ethereum/EIPs/blob/master/EIPS/eip-191.md emerged as the most easy to implement solution that also solves the above issues.

Please confirm @hackaugusto , @LefterisJP .

**Comment by loredanacirstea** [comment]
## EIP191:
`0x19 <1 byte version> <version specific data> <data to sign>`
For eip191, this means: `0x19 0x00 <intended validator address> <data to sign>`

## Raiden client messages format:
`0x19 0x00 <token_network_address> <chain_id> <message_id> <message specific data to sign>`

### Balance Proof Message:

```
bytes32 message_hash = keccak256(abi.encodePacked(
            byte(0x19),
            byte(0),
            token_network_address,
            chain_id,
            balance_proof_message_id,
            channel_identifier,
            balance_hash,
            nonce,
            additional_hash
        ));
```

### Balance Proof Update Message:

```
bytes32 message_hash = keccak256(abi.encodePacked(
            byte(0x19),
            byte(0),
            token_network_address,
            chain_id,
            balance_proof_update_message_id,
            channel_identifier,
            balance_hash,
            nonce,
            additional_hash,
            closing_signature
        ));
```

### Withdraw Message:

```
bytes32 message_hash = keccak256(abi.encodePacked(
            byte(0x19),
            byte(0),
            token_network_address,
            chain_id,
            withdraw_message_id,
            channel_identifier,
            participant,
            total_withdraw
        ));
```

### Cooperative Settle Message:

```
bytes32 message_hash = keccak256(abi.encodePacked(
            byte(0x19),
            byte(0),
            token_network_address,
            chain_id,
            cooperative_settle_message_id,
            channel_identifier,
            participant1,
            participant1_balance,
            participant2,
            participant2_balance
        ));
```

**Comment by andrevmatos** [comment]
Related: https://github.com/raiden-network/raiden/issues/1531

**Comment by loredanacirstea** [comment]
For compatibility with `eth_sign`:
`eth_sign(keccak256("\x19Ethereum Signed Message:\n" + len(message) + message)))`

Therefore the messages will have this form:
`\x19Ethereum Signed Message:\n" + len(message) + message`
`message = <token_network_address> <chain_id> <message_type_id> <message specific data to sign>`

Note, that the above format is not really EIP191 anymore. However, I think it solves our collision issues through the `eth_sign` prefix & the `message_type_id`.

I made https://github.com/raiden-network/raiden-contracts/pull/252 that implements this.

Please check it out, specifically https://github.com/raiden-network/raiden-contracts/pull/252/commits/dd8c61f84042a6be63b9ad53c3bb133571654498

**Comment by hackaugusto** [comment]
I think we should always avoid the null value 0. In this case I think we should start `byte version` and `message_type_id` at 1.

The idea is to avoid using 0, because this is the default value for uninitialized memory, which may lead to subtle bugs in the future, e.g. for version checking.

**Comment by andrevmatos** [comment]
@loredanacirstea I don't get how your `eth_sign` format isn't really EIP191 anymore, as they made it specifically to support it too, through version byte `0x45 (E)`. The `chain_id` **may** go encoded in the `v` value (as per [EIP155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md), but it's not mandatory, the old `v` values of [27,28] are still EIP191 compatible).

**Comment by andrevmatos** [comment]
Right, so they must have forgotten to update it accordingly on 712, there were eons since an EIP gathered that much reviews and scrutiny. Anyway, `0x19 0x00 <address>` is **one** signature schema proposed in EIP191, the one with version `0x00`. Version `0x45` (aka `eth_sign`) is also EIP191-compliant, although it's in process of being deprecated, it's the best supported signing scheme right now (until 712 gets implemented as per specification in the major clients), and improves our current situation. 
So:
> Note, that the above format is not really EIP191 anymore. However, I think it solves our collision issues through the eth_sign prefix & the message_type_id.

is not precise, as `eth_sign` format **is** EIP191, and that's `+1` on `eth_sign` approach. You meant _"is not EIP191 version byte `0x00`"_, one of the signatures proposed in that EIP.

PS: We **could** go for the more modern and stronger EIP712 anyway even if it's not implemented in the clients, as we don't do eth-node signing yet, we sign everything on our own, and then we could use it right now.

**Comment by LefterisJP** [comment]
(moved this to next week's release as no redeployment of contracts will happen this week and the issue is still under discussion)

**Comment by loredanacirstea** [comment]
Updated my PR here https://github.com/raiden-network/raiden-contracts/pull/252 with @hackaugusto 's suggestion. Message type ids now start with `1`.

**Comment by hackaugusto** [comment]
The balance proof *data structure* cannot have two different ids. The smart contracts **must** allow the balance proof data to be used either for a call to close or update. So, I think the message definition for `Balance Proof Message` and `Balance Proof Update Message` is incorrect.

@loredanacirstea could you elaborate on how `closing_signature  // bytes`for `Balance Proof Update Message` is computed?

**Comment by loredanacirstea** [comment]
```
function updateNonClosingBalanceProof(
        uint256 channel_identifier,
        address closing_participant,
        address non_closing_participant,
        bytes32 balance_hash,
        uint256 nonce,
        bytes32 additional_hash,
        bytes closing_signature,
        bytes non_closing_signature
    )
```
@hackaugusto ,

The message corresponding to the `closing_signature` is a `Balance Proof Message` -> uses the `balance_proof_message_type_id`.
The message corresponding to the `non_closing_signature` is a `Balance Proof Update Message`. This contains the `Balance Proof Message` data + the `closing_signature` -> uses the `balance_proof_update_message_type_id`.

I think the message signed by the `non-closing` participant is different from the normal balance proof, therefore should have it's own `message_type_id`.

**Comment by hackaugusto** [comment]
> The message corresponding to the closing_signature is a Balance Proof Message -> uses the balance_proof_message_type_id.
> The message corresponding to the non_closing_signature is a Balance Proof Update Message. This contains the Balance Proof Message data + the closing_signature -> uses the balance_proof_update_message_type_id.

Perfect. This is exactly what I wanted to clarify.

> I think the message signed by the non-closing participant is different from the normal balance proof, therefore should have it's own message_type_id.

Definitely.
