### ISSUE TITLE
Implement the deprecation switch for Red Eyes

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden-contracts#263]
Implement a deprecation switch in the contracts. Only a specific address given at the token network registry's creation will be able to invoke the switch.

Once the switch is invoked and the contracts are marked as deprecated then users are no longer able to open new channels and not able to deposit any more tokens. The contract is going to stay on chain and user can close the channels to get access to their tokens, as well as continue to transfer tokens within the channels.

Edit for clarity: Once the switch has been activated it can not be de-activated.

**Comment by loredanacirstea** [comment]
@LefterisJP please confirm that the deprecation switch MUST NOT be toggable. So, if you set it from `false` to `true`, it cannot be undone anymore.

**Comment by LefterisJP** [comment]
Confirmed as per our offline discussions.

**Comment by LefterisJP** [comment]
Number (2) -- we can live with this possibility.
