### ISSUE TITLE
Simplify tests for settle&unlock

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#273]
As mentioned in https://github.com/raiden-network/raiden-contracts/pull/189#discussion_r218134369,
the tests may be simplified by using parametrized ranges.
Suggestion: https://github.com/raiden-network/raiden-contracts/pull/189#discussion_r218443021

**Comment by hackaugusto** [comment]
Just one note: Usually parametrized tests are way slower to run.

**Comment by loredanacirstea** [comment]
Fixed in https://github.com/raiden-network/raiden-contracts/pull/278
