### ISSUE TITLE
Reenable setTotalWithdraw

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#277]
We commented out `setTotalWithdraw` in https://github.com/raiden-network/raiden-contracts/pull/270

These should be changed back when re-enabling withdraw:

## Contracts

- uncomment withdraw event https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/contracts/TokenNetwork.sol#L148-L152
- uncomment `setTotalWithdraw` https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/contracts/TokenNetwork.sol#L333
- uncomment `recoverAddressFromWithdrawMessage` https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/contracts/TokenNetwork.sol#L1472

## Test contracts
- uncomment `recoverAddressFromWithdrawMessagePublic` https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol#L224

## Tests
- https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/tests/fixtures/channel.py#L118-L126
- unskip all withdraw tests in https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/tests/test_channel_withdraw.py
- fix settlement test https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/tests/test_channel_settle.py#L146-L158
- unskip `test_recover_address_from_withdraw_message` https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/tests/unit/test_unit_signatures.py#L6-L7
- fix `ChannelValues` (now withdraw is set to `0` for all tests) https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/tests/utils/utils.py#L30-L31

**Comment by pirapira** [comment]
Is this still in Ithaka?

**Comment by loredanacirstea** [comment]
@pirapira - at the moment, only re-enabling `withdraw`. But it needs to be synchronized with the Raiden client team withdraw implementation.

**Comment by loredanacirstea** [comment]
I opened another issue for `cooperativeSettle`: https://github.com/raiden-network/raiden-contracts/issues/399 and left this issue only for `setTotalWithdraw`, as they their importance within the Ithaca milestone is now different.

**Comment by pirapira** [comment]
I raised the priority slightly because we have to try this one before making any progress on #401.
