### ISSUE TITLE
Maintain multiple source code & ABI versions

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#298]
@hackaugusto suggested to have separate folders for each `major` release (Mainnet).

PROs:
- direct access to all our existing token networks from the Raiden client (e.g. support interoperation between multiple token network versions, user operations on old token networks etc.)

CONs:
- code duplication (imo, not that bad)

**Comment by pirapira** [comment]
I've started storing sources and ABIs for all deployments (incl. test net).
