### ISSUE TITLE
Check if we save gas cost in using a separate ClosingRequest struct

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#3]
Using a `ClosingRequest` struct vs. storing all the channel data in the `Channel` struct.

Needs to be done:
- gas cost comparison between implementations for `openChannel` and `closeChannel`

https://github.com/raiden-network/raiden/pull/1286#discussion_r173967806

**Comment by loredanacirstea** [comment]
tl;dr: yes, we save gas when using a separate struct.
@hackaugusto 

For every empty variable initialized in a `struct` there is an additional 5000 gas cost.

Using `ClosingRequest`:
```
openChannel 110848
setDeposit 68243
closeChannel 106743
updateTransfer 67055
settleChannel 63017
```

Only using `Channel`:
```
channels[last_channel_index] = Channel({settle_timeout: settle_timeout, closing_participant: 0x0, settle_block_number: 0x0});
```
```
openChannel 121193
setDeposit 68221
closeChannel 106743
updateTransfer 67033
settleChannel 70645
```

Notes:
Initializing a struct means initializing every struct component.

Some simple tests:

```
contract Test {
    
    mapping (uint256 => Channel) public channels;
    
    struct Channel {
        uint256 settle_timeout;
        address closing_participant;
        uint256 settle_block_number;
        mapping(address => uint256) participants;
    }
    
    function create(uint256 index) public {
        channels[index] = Channel(10, 0, 0);
    }
    
    function create2(uint256 index) public {
        Channel memory channel;
        channel.settle_timeout = 10;
        channels[index] = channel;
    }
}
```

`create` - 52038
21000 (transaction) + 20000 + 2 * 5000
Variables added in storage for each SSTORE:
```
SSTORE - 20000
0x3f9553dc324cd1fd24b54243720c42e18e5c20165bc5e523e42b440a8654abd1: Object	
 key: 0xada5013122d395ba3c54772283fb069b10426056ef8ca54750cb9bb552a59e7d		
value: 0x000000000000000000000000000000000000000000000000000000000000000a   # settle_timeout
SSTORE - 5000
0xaa54e471e12dd2b1eb68c829886181ad0bf55684bdf6c129d495637e1bd9acae: Object	 
key: 0xada5013122d395ba3c54772283fb069b10426056ef8ca54750cb9bb552a59e7e	
 value: 0x0000000000000000000000000000000000000000000000000000000000000000   # closing_participant
SSTORE - 5000
0xba888a5aa101d2caf4b513938b315c6840e3e5073eb243bd57a2f2d614fd7fe1: Object	
 key: 0xada5013122d395ba3c54772283fb069b10426056ef8ca54750cb9bb552a59e7f	 
value: 0x0000000000000000000000000000000000000000000000000000000000000000   # settle_block_number
```


`create2` - 52199
- added `memory` costs

`create2` with `storage` instead of `memory` - 72714 (heh, adds another SSTORE and `channels[index] = channel` duplicates data)

**Comment by LefterisJP** [comment]
@loredanacirstea for all your tests please also specify compiler options and compiler version

**Comment by LefterisJP** [comment]
> create2 with Channel storage channel; - 72714 (heh, adds another 20000 SSTORE)

Ofcourse ^_^

Sidenote: Your gas estimates are much higher than my solidity version. Which version are you using?

**Comment by loredanacirstea** [comment]
Ah, true. Seems I got stuck on `0.4.17` (Remix) for these tests. No reason now to recalculate with a more recent version, but I will use a newer compiler version for the next tests.

**Comment by LefterisJP** [comment]
I did the recalculation. Difference seems similar, even though a bit smaller with v0.4.20. What's awesome is that even in the non-optimized version it's 5k gas cheaper! :)
