### ISSUE TITLE
Discuss saving gas by not having 0 value token transfers in settleChannel

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#30]
Add a conditional check such as: `if (token_amount > 0) { // do the token transfer }`

PROs:
- smaller gas cost for `settleChannel` by not doing `0` value token transfers - save ~8500 gas / transfer

CONs:
- > Note Transfers of 0 values MUST be treated as normal transfers and fire the Transfer event.

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#transfer
- It may be possible to do an attack where 1 of the transfers does not go through. The safe approach would be to register the effects on the blockchain as default. Then, anything not registered would be proof of an attack.

**Comment by LefterisJP** [comment]
> It may be possible to do an attack where 1 of the transfers does not go through. The safe approach would be to register the effects on the blockchain as default. Then, anything not registered would be proof of an attack.

Can you elaborate?

> Add a conditional check such as: if (token_amount > 0) { // do the token transfer }

The `if (token_amount > 0) { //do transfer }` pattern is not bad.

The EIP note you quoted:

> Note Transfers of 0 values MUST be treated as normal transfers and fire the Transfer event.

concerns only token implementations. i.e. how should the a smart contract implementing the `transfer()` function for a `0` value behave. It's nothing to do with how we use such contracts.
