### ISSUE TITLE
Fix post-deployment transaction information for Parity

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#347]
When deploying the contracts with Parity (Kovan, Mainnet), often, the deployment transaction receipt has `blockNumber = null` - e.g.
https://github.com/raiden-network/raiden-contracts/blob/fac73623d5b92b7c070fdde2b446648ec9117474/raiden_contracts/deploy/__main__.py#L374

The deployment script now stores this information as is and it has to manually be corrected. However, there are checks at the end of the deployment script `verify_deployed_contracts` (same as running the `deploy.verify` script), which fail.

TODO: 
- fix deployment info retrieval for Parity
- add CI test to make sure all the expected `data/deployment_[CHAIN].json` files exist and that all expected fields have valid values.

**Comment by pirapira** [comment]
Is this related? https://github.com/paritytech/parity-ethereum/issues/3569

**Comment by loredanacirstea** [comment]
Yes, it is the same issue. We should then get the block number with another API or poll the `getTransactionReceipt` to ensure correctness.

**Comment by pirapira** [comment]
Moved the rest of this issue to https://github.com/raiden-network/raiden-contracts/issues/466 .
