### ISSUE TITLE
Improve Etherscan verification script

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#349]
- add verification support also for `TokenNetwork` contracts

As suggested in the initial PR https://github.com/raiden-network/raiden-contracts/pull/345:

> For some reason, the verification fails for TokenNetworkRegistry. However, if you manually verify on Etherscan using the `flatten.sol` source created by the script in `raiden_contracts/deploy/` and the data printed by the script (solc version, ABI encoded constructor arguments etc.), then it works!

https://github.com/raiden-network/raiden-contracts/pull/345#pullrequestreview-170649230
> Ideally, the flattening should not be done like this, but following the compiled AST imports order or using a dedicated flattening package (I have not found one that works).
Can be improved in a future PR. For now, it does the job.

https://github.com/raiden-network/raiden-contracts/pull/345#discussion_r231039321
> I think for this we can use a dictionary where:

> ```
> {
> 3: "'https://api-ropsten.etherscan.io/api'",
> 4: "https://api-rinkeby.etherscan.io/api",
> ... etc
> }
> ```
> And use `.get(chan_id)` to fetch the URL that needs to be called.

https://github.com/raiden-network/raiden-contracts/pull/345#discussion_r231039624
> Can this be refactored somehow into it's own function? as this block uses the same code as the block above it.

https://github.com/raiden-network/raiden-contracts/pull/345#discussion_r231040946
> Might be a good idea to use pprint to have the data printed a bit more readable?

**Comment by pirapira** [comment]
I'll first run&read the current script and see if these issues need urgent care.

**Comment by pirapira** [comment]
> For some reason, the verification fails for TokenNetworkRegistry. However, if you manually verify on Etherscan using the `flatten.sol` source created by the script in `raiden_contracts/deploy/` and the data printed by the script (solc version, ABI encoded constructor arguments etc.), then it works!

Not anymore after https://github.com/raiden-network/raiden-contracts/pull/533/commits/37117eb628c3489725292b64a8c636150cfbe38a

**Comment by pirapira** [comment]
> Ideally, the flattening should not be done like this, but following the compiled AST imports order or using a dedicated flattening package (I have not found one that works).
Can be improved in a future PR. For now, it does the job.

Solved in https://github.com/raiden-network/raiden-contracts/pull/531

**Comment by pirapira** [comment]
> I think for this we can use a dictionary where:

> ```
> {
> 3: "'https://api-ropsten.etherscan.io/api'",
> 4: "https://api-rinkeby.etherscan.io/api",
> ... etc
> }
> ```

Done in https://github.com/raiden-network/raiden-contracts/pull/532/commits/5dd45b63288b82ae130f17f896ad8db3fe73ca8a

**Comment by pirapira** [comment]
> Can this be refactored somehow into it's own function? as this block uses the same code as the block above it.

Partially done in https://github.com/raiden-network/raiden-contracts/pull/532/commits/830c012104ad6c5ed626559366e9a3aa189d21e2.  The rest is tracked in https://github.com/raiden-network/raiden-contracts/issues/535

**Comment by pirapira** [comment]
> Might be a good idea to use pprint to have the data printed a bit more readable?

This is the last point and is not yet done.
