### ISSUE TITLE
race condition between claimReward() and opening a channel again?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#367]
`claimReward()` works only when the TokenNetwork contract has no ChannelState between the two participants.

https://github.com/raiden-network/raiden-contracts/blob/c6e94549c7296204b61742da174ef102961bbeb3/raiden_contracts/contracts/services/MonitoringService.sol#L258

So if I don't want to pay a MS, I can call `TokenNetwork openChannel(me, partner, something)` before the MS calls `claimReward()`.  Then `claimReward()` will see `Openned`, and the MS won't get the reward.  Is this correct?

**Comment by loredanacirstea** [comment]
This is because the MS contract is outdated. This PR https://github.com/raiden-network/raiden-contracts/pull/360/files should fix the issue, as it also references the `channel_identifier`. This makes the distinction between the old and new channel.

**Comment by pirapira** [comment]
I see, and I agree.
