### ISSUE TITLE
Somebody new should try out the release process document and fill in the details

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#371]
@loredanacirstea has described the current release process https://github.com/raiden-network/raiden-contracts/issues/355#issuecomment-445464788.  And I opened a small PR adding this description in this repository https://github.com/raiden-network/raiden-contracts/pull/370 . 

This issue keeps track of the next step: somebody (me?) tries out the release process on a test net, and fills in the missing details in the release document.

**Comment by loredanacirstea** [comment]
I am working on a proper description of the release process and when done, someone else can test it to make sure it fits reality. Then, we can improve it.
