### ISSUE TITLE
How to find the source code from deployment_kovan.json

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#375]
A few days ago I saw @LefterisJP trying to find the Solidity source of a contract from `deployment_kovan.json` and it seemed not easy.

`"contracts_version": "0.4.0"` is not so useful because there are many git revisions with the same `contracts_version`.  The other fields can identify the contract onchain, but the Solidity source is usually not reachable from there.

**Comment by LefterisJP** [comment]
My predicament was with the pre_limits contracts -- as back then unfortunately they were done by hand. With the system of [updating](https://github.com/raiden-network/raiden-contracts/blob/ce4c328157eae5b8bc61202e00796301b44f318b/raiden_contracts/deploy/__main__.py#L476) the deployment data through the deployment script it should just be a matter of checking the last commit that touched that file.

```bash
$ git log raiden_contracts/data/deployment_kovan.json                                                                                                                                                                         

commit 345ed3a984ccff3134991e5a330a250ad4a28f25
Author: Loredana <loredana.cirstea@gmail.com>
Date:   Tue Oct 16 20:56:56 2018 +0200

    Recompile and deploy contracts after version bump

commit 560b45a82c18dcf891d7d705daeb98ff436bef1e
Author: Loredana <loredana.cirstea@gmail.com>
Date:   Thu Oct 11 16:15:06 2018 +0200

    Add Kovan deployment info
```

So `345ed3a984ccff3134991e5a330a250ad4a28f25`. 
https://github.com/raiden-network/raiden-contracts/tree/345ed3a984ccff3134991e5a330a250ad4a28f25/raiden_contracts/contracts

**Comment by pirapira** [comment]
OK.  If there is a way, it's fine.
