### ISSUE TITLE
Replace raiden-libs get_private_key 

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#381]
Remove `raiden-libs` fixture dependencies and refactor fixtures for clarity.
Part of https://github.com/raiden-network/raiden-contracts/issues/354

`raiden-libs` is being deprecated. We need to replace `get_private_key`. It is currently used in:

```
# ./raiden_contracts/deploy/__main__.py
from raiden_libs.utils.private_key import get_private_key
```

**Comment by pirapira** [comment]
Is a copy-and-paste from `raiden-libs` acceptable?  Then I can take it.

**Comment by loredanacirstea** [comment]
@pirapira , yes. If needed, we can refactor later.
