### ISSUE TITLE
   NameError when deploy on testnet :  private_key = get_private_key(private_key)

### ISSUE THREAD

**Issue by xiaocaijigrowup** [raiden-network/raiden-contracts#388]
when deploy contract on testnet 
I follow the step on readme,and on second step:
**python -m raiden_contracts.deploy raiden --rpc-provider http://127.0.0.1:8545 --private-key /path/to/your/private_key/file --gas-price 10 --gas-limit 6000000**

I've annotated the statements that depend on raiden-libs according the link . 
https://github.com/raiden-network/raiden-contracts/issues/354
but  I get an error

File "/usr/local/lib/python3.6/dist-packages/raiden_contracts/deploy/__main__.py", line 179, in setup_ctx
    private_key = get_private_key(private_key)
NameError: name 'get_private_key' is not defined .

**Comment by xiaocaijigrowup** [comment]
I've noticed your code on github had been updated,but I use the command on your github readme.md
pip install raiden-contracts

I got outdated code .

**Comment by LefterisJP** [comment]
I assume that you installed raiden contracts with `pip install raiden-contracts`. That would install only the non-dev requirements and currently raiden-libs is [part of](https://github.com/raiden-network/raiden-contracts/blob/14b23e105754bbbc6703eedec61454239b89e326/requirements-dev.txt#L8) the dev requirements.

For now as a workaround for the issue do `pip install -r requirements-dev.txt` and you will also get raiden libs in your venv.

**Comment by loredanacirstea** [comment]
This was discussed in raiden's gitter channel and fixed by `pip install -r requirements-dev.txt`, as mentioned in the docs. I am closing this issue.

Another issue popped up though: https://github.com/raiden-network/raiden-contracts/issues/389
