### ISSUE TITLE
Keep networks alive between bounty releases and actual release - limits switch

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#391]
(brought up by @ulope )
We currently need to redeploy the core contracts between a bug bounty release and an actual production release, in order to remove the channel & token network limits.
This means:
- changing of code prior to a production release, that will not be tested on mainnet
- throwing away the bug bounty mainnet networks that have already been created
- keeping multiple versions of the contracts even within the same production version (limits + no-limits)

The suggestion is to have a limits switch directly in the contracts code, without the need for redeployment:
- we deploy the contracts with the limits enabled
- when we are ready for production, we make an on-chain transaction & we disable the limits check

Further discussions are needed to clarify this setup from a legal perspective:
- if the limits are disabled - are they disabled for good, without the option to reenable them? (I think it should be so
- tbd

**Comment by LefterisJP** [comment]
> when we are ready for production, we make an on-chain transaction & we disable the limits check

That's a really nice idea!

At least as long as we have the deprecation switch we already have some administrative/operation control over the contracts. As also discussed in the [limits](https://github.com/raiden-network/team/issues/54) issue.

It should make no legal difference if we also have a limits switch and that would make things so much easier for us.

> if the limits are disabled - are they disabled for good, without the option to reenable them? (I think it should be so

I would also say so -- but that's a Jim decision.

**Comment by loredanacirstea** [comment]
Adding this to the `Ithaca Testnet 02` milestone, as solving this would help us get rid of the `0.3._` contracts version & make testing easier.
It's possible that we might make a release without it, but we should prepare a PR & specs as soon as possible, for them to be reviewed by legal.

**Comment by loredanacirstea** [comment]
## Current Setup (summary)

- channel & network limits are enabled and cannot be disabled
- we can deprecate the network

```js
contract TokenNetworkRegistry {
    address public deprecation_executor;
    bool public token_network_created = false;

    modifier canCreateTokenNetwork() {
        require(token_network_created == false);
        _;
    }
    function createERC20TokenNetwork(address _token_address)
        canCreateTokenNetwork
        external
        returns (address token_network_address)
    { 
        ...
        // We limit the number of token networks to 1 for the Bug Bounty release
        token_network_created = true;
        ...
    }
}

contract TokenNetwork {
    uint256 constant public channel_participant_deposit_limit = 75000000000000000 wei;
    uint256 constant public token_network_deposit_limit = 250000000000000000000 wei;
    address public deprecation_executor;

    modifier onlyDeprecationExecutor() {
        require(msg.sender == deprecation_executor);
        _;
    }

    modifier isSafe() {
        require(safety_deprecation_switch == false);
        _;
    }

    function deprecate() isSafe onlyDeprecationExecutor public {
        safety_deprecation_switch = true;
    }

    function openChannel(address participant1, address participant2, uint256 settle_timeout)
        isSafe
        settleTimeoutValid(settle_timeout)
        public
        returns (uint256)
    {
       ...
        require(token.balanceOf(address(this)) < token_network_deposit_limit);
       ...
    }

    function setTotalDeposit(
        uint256 channel_identifier,
        address participant,
        uint256 total_deposit,
        address partner
    )
        isSafe
        isOpen(channel_identifier)
        public
    {
       ...
        require(total_deposit <= channel_participant_deposit_limit);
       ...
    }
}
```

## Possible New Setup

This is just a proposal. The issue should be further discussed.

(1) New Deployment State:
- we have channel & network limits on number of tokens + 1 token network limit
- we have a functional deprecation switch

(2) Deprecation State - for some good reason, we enable deprecation
- this will deprecate the contracts for good, no more opening & depositing allowed
- we will not be able to remove the limits -> (3) cannot happen anymore

(3) No Limits State
- we can disable the (1) limits when we think it is safe
- this should probably also disable any other tempering with the contracts (including the deprecation switch), so we remove any operator role -> (2) cannot happen anymore

```js
contract TokenNetworkRegistry {
    bool public limits_enabled = true;  // State (1) 
    address public deprecation_executor;
    address public token_network_created;

    modifier canCreateTokenNetwork() {
        require(token_network_created == address(0x0) || limits_enabled == false);
        _;
    }

    // State (2) 
    function deprecate() onlyDeprecationExecutor public {
        require(limits_enabled == true);
        TokenNetwork(token_network_created).deprecate();
    }

    // State (3) 
    function disableLimits() onlyDeprecationExecutor public {
        limits_enabled = false;
        // Disable limits on the only TokenNetwork created with limits enabled
        TokenNetwork(token_network_created).disableLimits();
    }

    function createERC20TokenNetwork(address _token_address)
        canCreateTokenNetwork
        external
        returns (address token_network_address)
    { 
        ...
        TokenNetwork token_network;

        // Token contract checks are in the corresponding TokenNetwork contract
        token_network = new TokenNetwork(
            _token_address,
            secret_registry_address,
            chain_id,
            settlement_timeout_min,
            settlement_timeout_max,
            address(this),  // deprecation executor, limits disabler can be the TokenNetworkRegistry itself
            limits_enabled
        );
        // We limit the number of token networks to 1 for the Bug Bounty release
        token_network_created = address(token_network);
        ...
    }
}

contract TokenNetwork {
    uint256 constant public channel_participant_deposit_limit = 75000000000000000 wei;
    uint256 constant public token_network_deposit_limit = 250000000000000000000 wei;
    address public token_network_registry; // old deprecation_executor;
    bool public safety_deprecation_switch = false;
    bool public limits_enabled;

    modifier onlyTokenNetworkRegistry() {
        require(msg.sender == token_network_registry);
        _;
    }

    modifier isSafe() {
        require(safety_deprecation_switch == false);
        _;
    }

    function deprecate() onlyTokenNetworkRegistry public {
        safety_deprecation_switch = true;
    }

    function disableLimits() onlyTokenNetworkRegistry public {
        limits_enabled = false;
    }

    function openChannel(address participant1, address participant2, uint256 settle_timeout)
        isSafe
        settleTimeoutValid(settle_timeout)
        public
        returns (uint256)
    {
       ...
        require(token.balanceOf(address(this)) < token_network_deposit_limit || limits_enabled == false);
       ...
    }

    function setTotalDeposit(
        uint256 channel_identifier,
        address participant,
        uint256 total_deposit,
        address partner
    )
        isSafe
        isOpen(channel_identifier)
        public
    {
       ...
        require(total_deposit <= channel_participant_deposit_limit || limits_enabled == false);
       ...
    }
}
```

**Comment by pirapira** [comment]
@pirapira will send Jim an email directly (<-- meeting outcome with Heiko and Stefan).

**Comment by pirapira** [comment]
sent the email.

**Comment by pirapira** [comment]
This should better dealt in the private repo.

**Comment by pirapira** [comment]
See #646, #648.
