### ISSUE TITLE
Reenable cooperativeSettle

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#399]
We commented out `cooperativeSettle` in https://github.com/raiden-network/raiden-contracts/pull/270

These should be changed back when re-enabling cooperative settle:

## Contracts

- uncomment `cooperativeSettle` https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/contracts/TokenNetwork.sol#L814
- uncomment `recoverAddressFromCooperativeSettleSignature` https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/contracts/TokenNetwork.sol#L1441

## Test contracts
- uncomment `recoverAddressFromCooperativeSettleSignaturePublic` recoverAddressFromCooperativeSettleSignaturePublic

## Tests

- unskip all cooperative settle tests in https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/tests/test_channel_cooperative_settle.py
- unskip `test_recover_address_from_cooperative_settle_signature` https://github.com/raiden-network/raiden-contracts/blob/d47aa6b6adbbfc3702e2258387d7695c96101d7b/raiden_contracts/tests/unit/test_unit_signatures.py#L173-L174

**Comment by hackaugusto** [comment]
Note, withdraw was re-enabled by https://github.com/raiden-network/raiden-contracts/pull/711 . coop seetle is redundant with withdraw, since we can implement it with two withdraws done by a proxy smart contract. This is not really necessary anymore.
