### ISSUE TITLE
Add `chain_id` in the balance proof signature

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#4]
Following the agreed upon specs (https://github.com/raiden-network/spec/blob/master/smart_contracts.rst#balance-proof), `chain_id` must be added to the balance proof.

As mentioned also in https://github.com/raiden-network/raiden/pull/1286#discussion_r173968199

Changes needed to:
- `closeChannel`
- `updateTransfer` & related functions
- `recoverAddressFromSignature`

**Comment by loredanacirstea** [comment]
If we want to use `chain_id`, we need to store it in the contract, because it cannot be accessed from the EVM.

Therefore, the constructor will be:
```
function TokenNetwork(address _token_address, address _secret_registry, uint256 chain_identifier) public
```

This means that you have to be careful when deploying the contract on the different chains.

**Comment by LefterisJP** [comment]
Seems correct to me. We would automate the deployment and the chain id would be filled automatically so I don't think there is any danger there.

**Comment by loredanacirstea** [comment]
Actually registering an independent `TokenNetwork` type contract is a bad idea. It could contain malicious code and we should not add it to the registry unless it was deployed in a controlled manner through `TokenNetworksRegistry.createERC20TokenNetwork`.

**Comment by LefterisJP** [comment]
yeah that is a good point. So let's not provide any means of registering an externally deployed `TokenNetwork` contract. Can you edit your response and strike it through with an explanation?
