### ISSUE TITLE
Disallow multiple channels between two nodes

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-contracts#40]
In a [discussion](https://github.com/raiden-network/spec/issues/55#issuecomment-382381243) we concluded to disallow having multiple channels between a pair of nodes for now. A check for this should be added to the contracts.

**Comment by loredanacirstea** [comment]
@LefterisJP , we are changing the original specs here. 
Just so you know, this will need another data structure refactor - as the contracts are now, I cannot check if 2 addresses have another channel open because I would need to know the identifier.

Not a trivial change, will require some thought.

**Comment by loredanacirstea** [comment]
(an idea - not sure how good, so I don't forget)

```
channel_identifier = keccak256(participant1, participant2)
```
`unlock` data can be stored as:

```
// locksroot => locked_amount
struct BalanceData {
    mapping (bytes32 => uint256)
}

// channel_identifier => BalanceData
mapping(bytes32 => BalanceData)
```
