### ISSUE TITLE
Add note about deploying the development pre_limits version

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#413]
From: https://github.com/raiden-network/raiden-contracts/issues/397#issuecomment-452304128

Deploying the pre-limits version is not documented. We should add this in Readme and make sure it's clear that it should only be use in development and not production

Note - this will be outdated by https://github.com/raiden-network/raiden-contracts/issues/391 if implemented.

**Comment by LefterisJP** [comment]
@loredanacirstea also mention that it actually does have limits -- just higher.

**Comment by loredanacirstea** [comment]
Fixed by https://github.com/raiden-network/raiden-contracts/pull/426
