### ISSUE TITLE
Support for multiple contract versions

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#437]
We have a bigger issue: [Maintain multiple source code & ABI versions](https://github.com/raiden-network/raiden-contracts/issues/298) that is targeted to add support for the upgradability of the Raiden client through inter-network connections between multiple versions. This was scoped out of Ithaca, because it adds more complexity and it isn't needed right now.

## Scope

This issue focuses on the way forward for Ithaca development.

### The current plan for Ithaca is:

- Red Eyes contracts `v0.4.0` will not be supported
- We will only have one supported contracts version (limits + nolimits will be merged through https://github.com/raiden-network/raiden-contracts/issues/391)

### The way forward for the development phase of Ithaca

- temporarily support `v0.4.0` ? (I assume yes, but the Raiden client team must decide on this)
- temporarily support `v0.3._`)? (I assume yes, but only until we merge the limits + nolimits version, which will then become the `development` version for the Raiden client)
- support the current `development` version

Note: I am talking about the contracts version, not the package version.

## Proposed solution

- add a `data_0.4.0` folder with the precompiled data + deployment info for `v0.4.0` + reference to the last source code commit. (this will require the Raiden client to use this specific version for `production` and not the default; very small change, as it already supports `v0.3._`, formerly known as `pre-limits` here: https://github.com/raiden-network/raiden/blob/072d714f464c9ecb5a0c39da3cbab29ca3bdc5c4/raiden/ui/app.py#L292-L295)
- the current `data` folder will contain the in-development version (precompiled data + testnets only deployment info).

The above is the easiest to implement, as we don't need to change the existing API.
Other solutions imply: support for multiple pypy packages (pypy doesn't support this itself), multiple folders with source code & tests to ensure integrity that will eventually be removed even within Ithaca.

**Comment by loredanacirstea** [comment]
@rakanalh , @hackaugusto - would the proposed solution work for you?

**Comment by LefterisJP** [comment]
> temporarily support v0.4.0 ? (I assume yes, but the Raiden client team must decide on this)

I think this makes sense for me. So as far the raiden client is concerned this will always be the `--environment-type production` running mode. Until the actual Ithaca release. Right?

> temporarily support v0.3._)? (I assume yes, but only until we merge the limits + nolimits version, which will then become the development version for the Raiden client)
>     support the current development version

I would say this should always be the `--environment-type development` version. So for now `v0.3_` until you create a new release.


> multiple folders with source code & tests to ensure integrity that will eventually be removed even within Ithaca

I wouldn't mind multiple folders with source code. Tests would not be needed for older versions as we assume that versions are immutable once released and deployed, right?

But I am can live with both solutions.
