### ISSUE TITLE
Add a CI test for the deployment script

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#438]
CI test for the deployment script, as it seems to be prone to breaking between releases and manual testing is iffy.

We currently have a deployment test here: https://github.com/raiden-network/raiden-contracts/blob/d08a3abaffdd9ebd4b6cd0a4209d34a1a1328715/raiden_contracts/tests/test_deploy_script.py#L18. This checks:
- that `deploy_raiden_contracts()` used by `python -m raiden_contracts.deploy raiden` works correctly https://github.com/raiden-network/raiden-contracts/blob/d08a3abaffdd9ebd4b6cd0a4209d34a1a1328715/raiden_contracts/deploy/__main__.py#L244
- that `verify_deployed_contracts()` works correctly and checks that an error is thrown if the post-deployment info is tampered with

We should have cli tests for our deployment script, checking that the following work as expected:
- [x] `python -m raiden_contracts.deploy raiden`
- [x] `python -m raiden_contracts.deploy services`
- [x] `python -m raiden_contracts.deploy token`
- [x] `python -m raiden_contracts.deploy register`

These tests should also make sure all the flags work, especially the `--contracts-version`

**Comment by pirapira** [comment]
In test_deploy_script.py we use https://github.com/ethereum/eth-tester .  For this issue, I think a `geth` or a `parity` process is appropriate.

**Comment by pirapira** [comment]
There are tests calling all those commands with `CliRunner()`.  As of now, different contract_versions matter much less than before.
