### ISSUE TITLE
Asses using Enum for channel states in TokenNetwork

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#44]
As mentioned in https://github.com/raiden-network/raiden-contracts/pull/39#discussion_r183719909 and https://github.com/raiden-network/raiden-contracts/pull/39#discussion_r183679276:

Channel `state` should be of `Enum` type for making the code clearer.
Gas costs must be assessed in order to make sure that Enums can also be packed to 32 bytes, as the current `uint8` variable. Enums should be equivalent to `bytes1`, but this should be checked.

**Comment by czepluch** [comment]
According to http://solidity.readthedocs.io/en/v0.4.24/types.html#enums "The integer type used is just large enough to hold all enum values" so it should be fine to use an `Enum` for this.

**Comment by loredanacirstea** [comment]
Solved by https://github.com/raiden-network/raiden-contracts/pull/206
