### ISSUE TITLE
Deploy current development version on all testnets

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#444]
Deploy all current contracts on all testnets (Ropsten, Rinkeby, Kovan):
- core contracts
- MS & RSB contracts (after https://github.com/raiden-network/raiden-contracts/issues/436 is done)

Uncomment these checks:
https://github.com/raiden-network/raiden-contracts/blob/e6316793d70e62e1aff6762f715fc6831685b9a8/raiden_contracts/tests/test_contracts_compilation.py#L94-L98

**Comment by LefterisJP** [comment]
@loredanacirstea 

> Uncomment these checks:

Which checks?

**Comment by loredanacirstea** [comment]
Had them in a branch that was not pushed. I added them now.

**Comment by loredanacirstea** [comment]
Contracts were deployed on all testnets in https://github.com/raiden-network/raiden-contracts/pull/459, so we can reenable the above checks now.

**Comment by pirapira** [comment]
Will do ^.
