### ISSUE TITLE
User Deposit Contract

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-contracts#447]
The Raiden services will ask for payment in RDN. The Monitoring Service and potentially the Pathfinding Service require deposits to be made in advance of service usage. These deposits will be handled by the User Deposit Contract.
Usage of the deposit for payments is not safe from double spending, but measures can be taken to reduce the likelihood to acceptable levels. This is a good trade off as long as the money lost on double spending is less than the savings in gas cost. 

## Requirements
- [x] Users can deposit and withdraw tokens.
- [x] Tokens can be deposited to the benefit of other users. This could facilitate onboarding of new raiden users and allow a MS to defer the monitoring to another MS.
- [x] Tokens can't be withdrawn immediately, but only after a certain delay. This allows services to claim their deserved payments before the withdraw takes place.
- [x] Services can read the effective balance of a user (current balance - planned withdrawals)
- [x] Service contracts are trusted and can claim tokens for the service providers.
- [x] Services can listen to events which notify them of decreasing user balances. A service can then claim payments before double spending becomes too likely.

### Monitoring Service rewards

The MS is promised a reward for each settlement in which it took part on behalf of the non-closing participant. Before accepting a monitor request, the MS checks if enough tokens are deposited in the UDC. The MS that has submit the latest BP upon settlement will receive the promised tokens on it's UDC balance.

### 1-n payments
[This is just a suggestions so far. No decision made.]
The PFS will be paid with signed IOUs, roughly a simplified uRaiden adapted to 1-n payments. The IOU contains the amount of tokens that can be claimed from the signer's UDC balance. See https://github.com/raiden-network/raiden-services/issues/38 for details.

**Comment by palango** [comment]
Nice overview, no requirements I'd add. Some comments below.

> Users can deposit and withdraw tokens.

The token will always be the RDN token, right?

> Service contracts have permission to transfer tokens in the UDC between users.

What do you mean by that? I'd also add that the service contracts are trusted and can claim tokens for the providers.

> Before accepting a monitor request, the MS checks if enough tokens are deposited in the UDC

The MS might also want to check the deposit before sending the update transaction.

**Comment by karlb** [comment]
Specification from this ticket is added to the spec repo in https://github.com/raiden-network/spec/pull/202.
Implementation in https://github.com/raiden-network/raiden-contracts/pull/448.
