### ISSUE TITLE
Create a contribution guide

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#453]
Create a contribution guide.

- mention known good practice patterns (invariant checks, check effects interactions etc.)
- maybe links to known tutorials on security
- move Solidity code style from https://github.com/raiden-network/raiden/blob/master/CONTRIBUTING.md#solidity and maybe add more suggestions around how to pick variable names etc.

> #### Solidity
> 
> For solidity we generally follow the style guide as shown in the [solidity
> documentation](http://solidity.readthedocs.io/en/develop/style-guide.html) with
> a few notable exceptions:
> 
> **Variable Names**
> 
> All variable name should be in snake case, just like in python. Function names
> on the other hand should be mixedCase. MixedCase is essentially like CamelCase
> but with the initial letter being a small letter. This helps us to easily
> determine which function calls are smart contract calls in the python code
> side.
> 
> ```js
> function iDoSomething(uint awesome_argument) {
>     doSomethingElse();
> }
> ```

**Comment by pirapira** [comment]
Links
* https://github.com/trailofbits/awesome-ethereum-security
* https://consensys.github.io/smart-contract-best-practices/

**Comment by loredanacirstea** [comment]
Also add basic links to Solidity docs:

- https://solidity.readthedocs.io
- https://github.com/ethereum/solidity, with mention that https://github.com/ethereum/solidity/projects shows the upcoming planned changes
- http://remix.ethereum.org - for quick tests & detailed debugging (how to: https://github.com/ethereum/remix-workshops/blob/8344b650e74e20659290eb3163cef27db2291bb2/debuggingLiveTransactions/DebuggingTransactions.pdf)

**Comment by pirapira** [comment]
I think it's done.
