### ISSUE TITLE
Deploy RSB contracts + core contracts on the test nets by the first half of February 2019

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#476]
By @Dominik1999 's request.

@karlb : what are the RSB contracts?  Can you list them?

**Comment by pirapira** [comment]
I said I'll answer @Dominik1999 tomorrow if this is feasible.

**Comment by pirapira** [comment]
It seems the RSB registry needs to be mocked.  A basic plan is missing, waiting for a discussion https://github.com/raiden-network/team/issues/300.

**Comment by pirapira** [comment]
From my perspective:

**What I'm supposed to achieve**
- till 14. Feb, deploy the service contracts that are available on 12. Feb.

**Who is 'my customer' going forward?**
- sounds like @karlb 

**Plan breakdown**
- practice deploying contracts
     * [ ] (should work on 4. Feb) deploy UDC
     * [ ] (should work on 4. Feb) deploy RSB
     * [ ] (should work on 4. Feb) deploy MS
     * [ ] (should work on 5. Feb) post-deployment initialization calls
     * [ ] (should work on 6. Feb) check initialized storage values of UDC, RSB and MS
     * [ ] (should work on 7. Feb) etherscan verifications
     * [ ] (best effort) practice the process with OneToN when it comes in

- [ ] (on 12. Feb.) identify the contracts that should be deployed 14th, and inform @karlb, @palango , @Dominik1999 and @czepluch 
- [ ] (on 13. Feb.) final adjustments and deployment

14. Feb. is left for emergency.

**Comment by pirapira** [comment]
I need to save enough testnet ETH.

**Comment by pirapira** [comment]
I decided not to upgrade to solc 0.5.3 after reading the changelog. https://github.com/ethereum/solidity/blob/develop/Changelog.md#053-2019-01-22

**Comment by LefterisJP** [comment]
Which part of the changes made you not want to upgrade?

**Comment by pirapira** [comment]
The contracts to be deployed:
* TokenNetworkRegistry
* a Token
* TokenNetwork
* SecretRegistry
* EndtpointRegistry
* MonitoringService
* OneToN
* ServiceRegistry
* UserDeposit

The test nets where the contracts will be deployed:
* Kovan
* Ropsten
* Rinkeby

**Comment by pirapira** [comment]
The deployments have been done.

**Comment by Dominik1999** [comment]
thank you very much!
