### ISSUE TITLE
Update gas usage information for 0.10.0

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#487]
The information in [constants.py](https://github.com/raiden-network/raiden-contracts/pull/335/files#diff-70026bbd7d4baf9b2d96dd052bf74f5cR28) needs to be updated manually for 0.10.0.

**Comment by pirapira** [comment]
@karlb after https://github.com/raiden-network/raiden-contracts/pull/510 , is there any more gas numbers needed before the next release?

**Comment by karlb** [comment]
I'm not sure about "needed", but I could add the costs for the UDC deposit and withdraw functions for completeness. That should be easy enough, so I'll just do it.

**Comment by pirapira** [comment]
I should have asked for "wanted" rather than "needed".

**Comment by pirapira** [comment]
Constantinople might still make storage a bit cheaper, but that shouldn't cause annoyance.
