### ISSUE TITLE
Do we need `GAS_REQUIRED_FOR_UDC_TRANSFER` etc?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#493]
`raiden_contracts/constants.py` lists gas costs for some smart contract operations.
```
GAS_REQUIRED_FOR_CREATE_TOKEN_NETWORK = 3234716
<snip>
GAS_REQUIRED_FOR_REGISTER_SECRET = 46161
GAS_REQUIRED_FOR_ENDPOINT_REGISTER = 49183
```
Do we need similar gas cost constants for the service contracts? @karlb @palango will you use these kinds of numbers?

**Comment by palango** [comment]
@pirapira Yes that would be nice. Especially the `monitor` and `claimReward` functions of the MS contract would be nice, as that would help us to make estimated of how much gas the MS account should have in reserve. (Same for the OneToN `claim`)

For the UDC and ServiceRegistry I don't see the need right now.

**Comment by pirapira** [comment]
@palango thanks for the feedback!

**Comment by pirapira** [comment]
I separated what's needed for 0.10.0 ( by Feb. 14) in https://github.com/raiden-network/raiden-contracts/issues/496 .
