### ISSUE TITLE
Support both Python 3.6 & Python 3.7

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#494]
Currently `raiden-contracts` is supposed to be used with Python 3.6.  This issue keeps track of supporting Python 3.7 as well.

Do we need to make sure that the deployed contracts don't differ due to different Python versions?

**Comment by pirapira** [comment]
> Do we need to make sure that the deployed contracts don't differ due to different Python versions?

Probably not. The deployment is done with the bytecode in `contracts.json`.  The contents of `contracts.json` are checked in Travis runs.

**Comment by pirapira** [comment]
Do we need to run both versions of Python in Travis?

Probably not necessary, but that's a good to have (we might find more issues).

**Comment by ulope** [comment]
@pirapira In case you decide to run the tests on multiple versions I'd very much recommend to use [tox](https://tox.readthedocs.io/en/latest/).

There is also a plugin to seamlessly integrate it with travis' matrix feature: https://tox-travis.readthedocs.io/en/stable/

**Comment by karlb** [comment]
We require python 3.7, now.
