### ISSUE TITLE
make [no ci] flag work

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#507]
Travis still runs even when I add `[no ci]` in the description of a PR.  This incurs unnecessary waiting time for PRs with only document changes.

**Comment by pirapira** [comment]
`[skip ci]` should work.  https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by pirapira** [comment]
If I say `[skip ci]`, GitHub waits for Travis forever.
```
continuous-integration/travis-ci Expected — Waiting for status to be reported
```

So it's not a good solution.

**Comment by LefterisJP** [comment]
This is what we have always been doing. You can still merge the PR with a force-merge if you know it's only docs.

As an alternative you can make a special [skip tests] flag that would only do some linting checks and run no other jobs.

**Comment by pirapira** [comment]
Ah, I remember how it was in `raiden` repo.  Good for me.
