### ISSUE TITLE
Are we using `pytest -n 4` or something in Travis runs?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#511]
@karlb saw that `pytest -n 4` works on his machine in `raiden-contracts`.  Can we speed up Travis runs with this technique?

**Comment by karlb** [comment]
Yes, we are:
```
$ coverage run --source raiden_contracts/ -m py.test -Wd --travis-fold=always -n 2 -v $TEST_TYPE
```
We're currently using two processes in parallel (`-n 2`).

**Comment by pirapira** [comment]
Thank you for checking up!
