### ISSUE TITLE
remove a warning ('Do not panic, it probably does not exist') from make compile_contracts execution

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#526]
When I run `make compile_contracts` I see warnings like this:

```
raiden-contracts/raiden_contracts/contract_manager.py:150: UserWarning: Comparing old solc version with new one. Cannot load precompiled smart contract metadata from Token. Do not panic, it probably does not exist. Expecting value: line 1 column 1 (char 0)
  f'Comparing old solc version with
```

Instead of saying "it probably does not exist", the script should make sure it doesn't exist, and drop the warning.

**Comment by karlb** [comment]
Done in https://github.com/raiden-network/raiden-contracts/commit/f8f2a4dcb6ce80b7e298803838ad0348860f3b6a.
