### ISSUE TITLE
unlocked_amount may be 0 too.

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden-contracts#53]
```
function unlock(
        uint256 channel_identifier,
        address participant,
        address partner,
        bytes merkle_tree_leaves)
        public

        // Transfer the unlocked tokens to the participant
        require(token.transfer(participant, unlocked_amount));

        // Transfer the rest of the tokens back to the partner
        if (returned_tokens > 0) {
            require(token.transfer(partner, returned_tokens));
        }
```
this code assumes that `returned_tokens` maybe 0,and `unlocked_amount` must  greater than 0。
for example ,the caller (msg.sender) maybe `partner`(argument), and all locks are locked.
in this condition, `returned_tokens` equals `nonce_or_locked_amount`。

and some ERC20 token doesn't allow transfer 0 token.

**Comment by loredanacirstea** [comment]
@nkbai , thank you for reporting! 
This will be fixed in https://github.com/raiden-network/raiden-contracts/pull/64
