### ISSUE TITLE
multiple --contract-name to etherscan_verify.py with a click feature

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#535]
This issue keeps track of using `click`s feature in `etherscan_verify.py` so the script can take multiple `--contract-name` options.  The resulting code should be much cleaner than now.

This idea comes from https://github.com/raiden-network/raiden-contracts/pull/532#discussion_r254658896.

**Comment by pirapira** [comment]
It's questionable whether anybody wants to use this feature. The default is to do it on all contracts, and that's fine for most usage.

**Comment by karlb** [comment]
> It's questionable whether anybody wants to use this feature. The default is to do it on all contracts, and that's fine for most usage.

As suspected, there has been no demand for this feature. The current behavior works fine.
