### ISSUE TITLE
Find the source from which data_0.3._ are compiled

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#543]
What are data_0.3._ deployment files?

* [ ] check if they have deposit limits?
* [ ] add source codes to the Etherscan
* [ ] add a document in the repo explaining the different deployment files (maybe that already exists, but see where it is)

**Comment by pirapira** [comment]
`0.3._` has deposit limits: https://rinkeby.etherscan.io/address/0xed50a9ad6263f5416de956b27979ee3457557896#code

**Comment by pirapira** [comment]
Perhaps it's better to remove 0.3._.

**Comment by pirapira** [comment]
Commit 89b3625dd702fe5397f21ec458a1b8e5e9e908e0 adds the deployment data in question.  Which source was used for this?

**Comment by pirapira** [comment]
README says something actually.

> Source code: https://github.com/raiden-network/raiden-contracts/tree/fc1c79329a165c738fc55c3505cf801cc79872e4/raiden_contracts/contracts

Perhaps it's possible to re-generate the same bytecode from there.

**Comment by palango** [comment]
0.3 was removed from the repo.
