### ISSUE TITLE
Use bump2version instead of bumpversion?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#554]
`RELEASE.rst` currently suggests using `bumpversion` for updating version strings in this codebase.

There is a rumor that the original `bumpversion` is no longer being maintained.

This issue keeps track of checking the rumor and switching to `bump2version` if necessary.

**Comment by pirapira** [comment]
Related: #584 .

**Comment by palango** [comment]
We already use `bump2version`
