### ISSUE TITLE
Internal review for Alderaan mainnet contracts

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#563]
This issue keeps track of getting the smart contracts for Ithaca mainnet deployment reviewed internally.

* [ ] identify the contracts to be reviewed internally
* [ ] identify the version of the contracts to be reviewed internally
* [ ] planning the internal review
* [ ] fixing the issues found in the internal review #564

**Comment by karlb** [comment]
Internal review has been done.
