### ISSUE TITLE
Internal review of ServiceRegistry for Alderaan mainnet deployment

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#565]
This is a part of https://github.com/raiden-network/raiden-contracts/issues/563.

This issue keeps track of getting the ServiceRegistry contract reviewed internally.

**Comment by pirapira** [comment]
This issue can be forgotten until Service Registry contract(s) are specified: https://github.com/raiden-network/spec/issues/217

**Comment by karlb** [comment]
This has already been done before the Alderaan release.
