### ISSUE TITLE
Try Solidity's SMT integration on TokenNetwork (dep: first upgrade solc)

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#566]
Especially, `setteleChannel()` function must not contain overflows or underflows.  Consider adding an artificial overflow and see an error (to make sure that the results are valuable).

**Comment by pirapira** [comment]
`pragma experimental SMTChecker;`.

**Comment by pirapira** [comment]
Currently I see an internal error in the Solidity compiler with `solc 0.5.4`.
```
 solc.exceptions.SolcError: An error occurred during execution
        > command: `solc --combined-json abi,bin,bin-runtime,metadata,ast .=. lib=data/source/lib raiden=data/source/raiden test=data/source/test services=data/source/services data/source/raiden/TokenNetwork.sol data/source/raiden/EndpointRegistry.sol data/source/raiden/Utils.sol data/source/raiden/SecretRegistry.sol data/source/raiden/Token.sol data/source/raiden/TokenNetworkRegistry.sol`
        > return code: `1`
        > stderr:

        > stdout:
        Internal compiler error during compilation:
/solidity/libsolidity/formal/SMTChecker.cpp(1296): Throw in function dev::solidity::smt::Expression dev::solidity::SMTChecker::currentValue(const dev::solidity::VariableDeclaration&)
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] =
Makefile:6: recipe for target 'compile_contracts' failed
make: *** [compile_contracts] Error 1
```

**Comment by axic** [comment]
There have been a lot of improvements in newer versions (especially the upcoming version). I suggest to try the last release meanwhile.

**Comment by pirapira** [comment]
@axic Thank you for the advice!

**Comment by pirapira** [comment]
Depends on https://github.com/raiden-network/raiden-contracts/issues/1155

**Comment by karlb** [comment]
I've compiled the current solidity with support for z3 and cvc4 and ran it on `TokenNetwork.sol`. The output is attached. Please ignore the `Warning: Source file does not specify required compiler version!` warnings, since I removed the version pragma to make the compiled prerelease version work.

Due to the high level of noise, it is probably not something that should make CI fail at the moment, but reading through the warnings after major sounds like a good idea.

Here are some interesting bits (there are lots of warnings about potential false positive, so these might be false positives, too):
```
Warning: Overflow (resulting value larger than 2**256 - 1) happens here
   --> data/source/raiden/TokenNetwork.sol:281:9:
    |
281 |         channel_counter += 1;
    |    

Warning: Assertion violation happens here
   --> data/source/raiden/TokenNetwork.sol:295:9:
    |
295 |         assert(channel.settle_block_number == 0);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion violation happens here
   --> data/source/raiden/TokenNetwork.sol:296:9:
    |
296 |         assert(channel.state == ChannelState.NonExistent);
    |         ^^

Warning: Underflow (resulting value less than 0) happens here
   --> data/source/raiden/TokenNetwork.sol:343:25:
    |
343 |         added_deposit = total_deposit - participant_state.deposit;
    |       

Warning: Overflow (resulting value larger than 2**256 - 1) happens here
   --> data/source/raiden/TokenNetwork.sol:343:25:
    |
343 |         added_deposit = total_deposit - participant_state.deposit;
    |      

Warning: Underflow (resulting value less than 0) happens here
   --> data/source/raiden/TokenNetwork.sol:354:16:
    |
354 |         assert(participant_state.deposit + added_deposit == total_deposit);
    |      
```

[smt-TokenNetwork.log](https://github.com/raiden-network/raiden-contracts/files/4307847/smt-TokenNetwork.log)

**Comment by karlb** [comment]
I've looked through the warnings and did not find anything immediately useful. This looks like it could be an excellent tool in the future, but right now it does not understand enough of the code constructs to produce a reasonable signal/noise ratio.
