### ISSUE TITLE
Use the same (or similar, or very different) version numbers for smart contracts and Python packages.

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#584]
Currently the Solidity files contain one version number (say, 0.7.0) and the Python package has another version number (say, v0.11.0).  This confuses some people.  Maybe we should use the same version or closer version numbers.  This issue keeps track of
* [x] deciding 
   a. combine these two version numbers into one
   b. bump smart contract versions to the package version
   c. don't change the current scheme.
   d. make the contract version numbers look very different from tha Python package versions
* [x] implementing the change if decided.

**Comment by pirapira** [comment]
Ping @rakanalh .

**Comment by pirapira** [comment]
I'll come up with the advantage of having two different version numbers.

**Comment by pirapira** [comment]
**advantage of keeping different contract numbers**

With the current set up, it's possible to deploy a new version of one smart contract and still keep using the old deployment of another smart contract.  If we synchronize the package version and the contract version, every new PyPI release must contain new deployements of **every** contract.  That's unreasonable for the user.

**Comment by pirapira** [comment]
@rakanalh are you convinced with ^ ?

**Comment by pirapira** [comment]
@karlb has an idea:

> We could also bump the contract version number to the current python package version each time we do a deploy.

**Comment by rakanalh** [comment]
I think the argument makes sense as the package version could be different than the solidity code version... i see two approaches:
Prequisite: 

Then:
1. Either bring the both versions to the same number and bump both numbers when the package is updated.
2. Document why we have 2 versions for a package

I guess number 2 would be the faster approach as you can direct people towards the documentation if asked about this topic again :)

**Comment by pirapira** [comment]
@rakanalh do you have a preference where to document the version numbers?  In README?

**Comment by rakanalh** [comment]
Yea i guess the README file should be the go-to file for such information.

**Comment by hackaugusto** [comment]
> **advantage of keeping different contract numbers**
> 
> With the current set up, it's possible to deploy a new version of one smart contract and still keep using the old deployment of another smart contract. If we synchronize the package version and the contract version, every new PyPI release must contain new deployements of **every** contract. That's unreasonable for the user.

This is *the* reason for having different versions, also **please** make **all** deployed version available.

**Comment by pirapira** [comment]
@hackaugusto 

> please make all deployed versions easily available.

I think that's cleaner. I created an issue: https://github.com/raiden-network/raiden-contracts/issues/596

**Comment by pirapira** [comment]
Maybe similar numbers are more confusing than very different ones.  If packages are like `v0.11.0`, the Solidity sources can go `version76`, `version77`.

**Comment by pirapira** [comment]
There is an FAQ entry describing the two versions, so it might not be an issue anymore.

**Comment by pirapira** [comment]
@karlb came to me and explained a scheme:

* all new deployments get at least a minor upgrade in `contracts_version` so the new `contracts_version` looks very similar to the next Python package version.
* all Python-only upgrades get a patch upgrade in the package version

There was [a counter argument](https://github.com/raiden-network/raiden-contracts/issues/584#issuecomment-465102531) with which [@hackaugusto agreed](https://github.com/raiden-network/raiden-contracts/issues/584#issuecomment-465924523). The argument is not valid anymore, because different `contracts_version`s already share the same SecretRegistry deployment.

**Comment by pirapira** [comment]
#1303 implements this change.
