### ISSUE TITLE
Obsolete (edit: ~Remove~) 0.3._ deployment data

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#591]
Currently `raiden_contracts/data_0.3._` exists only for providing access to an old deployment.

However, it [seems](https://github.com/raiden-network/raiden/pull/3511/files#diff-14a4915b775dfbab039e080a28553d78L49) the `0.3._` version will be out of use soon.

This issue keeps track of
* communicating with Raiden client team about removing `0.3._` deployment info
* and actually removing `0.3._` deployment info

**Comment by hackaugusto** [comment]
I would argue that it's better to keep this data around, just under a better file structure.

**Comment by LefterisJP** [comment]
Yes I don't see any reason to ever remove old deployment data. `0.3._` has been deployed and exists in many networks. This package should keep the data, but yes in the Raiden client we will stop using it soon.

**Comment by pirapira** [comment]
I'm fine with just emitting a warning like:
```
You are using a deployment 0.3._.  Nobody seems to have the Solidity sources used for this deployment.  Nobody can answer why things work or do not work.
```

I wrote this error when I was thinking about removing deployment data aggressively.  But I received a new request to have every deployments accessible #596 .

**Comment by pirapira** [comment]
It seems we'll keep this around.
