### ISSUE TITLE
Make all deployed versions accessible

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#596]
The current release procedure does not provide `data_x.y.z` directory for every contract version.  This issue keeps track of modifying the release procedure so that every package release (with a new deployment) adds a new `data_x.y.z` directory.

Of course, no new directories are needed when there have been no changes in the contract sources since the last package release.

https://github.com/raiden-network/raiden-contracts/issues/584#issuecomment-465924523

**Comment by pirapira** [comment]
After #614, all future deployments will be accessible.

Is there any need to recover older versions like `0.7.0`?

**Comment by pirapira** [comment]
@hackaugusto from 0.8.0 onward, all deployment data will be accessible forever.  Do you also want ancient versions recovered?

**Comment by hackaugusto** [comment]
> Do you also want ancient versions recovered?

Only for the versions that we have deployed to the main chain and compatibility will be preserved.

**Comment by pirapira** [comment]
Then I have everything covered I believe.
