### ISSUE TITLE
Provide an unlimited version for testing `raiden`

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#599]
Many CI tests in `raiden` repo expect versions of smart contracts without limits.  So `raiden-contracts` should provide smart contracts without any limits.

**Comment by pirapira** [comment]
I don't have any source of unlimited versions.  So I need to figure out a few things.

* should the unlimited version have really no limits (not even anything like `0.3._`'s limits)?
* should the unlimited version have the deprecation switch?
* I guess arbitrary numbers of ERC20 tokens can be registered to TokenNetworkRegistry
* I guess there are no other differences between the limited version and the unlimited version.

**Comment by LefterisJP** [comment]
>     * should the unlimited version have really no limits (not even anything like `0.3._`'s limits)?

yes

>     * should the unlimited version have the deprecation switch?

no

>     * I guess arbitrary numbers of ERC20 tokens can be registered to TokenNetworkRegistry

yes

>     * I guess there are no other differences between the limited version and the unlimited version.

exactly. Only differences that should exist is everything that has to do with control of the contracts, like limits and deprecation switch. In all other ways they should be ABI compatible.

**Comment by pirapira** [comment]
* where to store unlimited versions
    * `data_x.y.z-unlimited` should be fine.
* [ ] write a script to generate unlimited versions of Solidity code (and add a `Makefile` goal)
* [ ] modify `make compile_contracts` so it generates `contracts-unlimited.json` in addition to `contracts.json`
* [ ] modify `make verify_contracts` so it checks `contracts-unlimited.json` in addition to `contracts.json`
* [ ] change RELEASE.rst 
* [ ]

**Comment by pirapira** [comment]
^ is the proper way.  The quick way is to introduce `data_0.8._`.

**Comment by pirapira** [comment]
@LefterisJP should the constructor of `TokenNetwork` take `_deprecation_executor` argument?

**Comment by pirapira** [comment]
^ Ah, but it shouldn't matter.  You won't call that constructor yourself.

**Comment by LefterisJP** [comment]
@pirapira you seem to have answered your question. But I am not sure exactly what the question was. So the `_deprecation_executor` sounds like an address that can deprecate the token network, right? This would only be for a single token network since that's where the limits are.

And at the moment the way we deprecate the token network is at the registry contract.

**Comment by pirapira** [comment]
I'm changing `TokenNetwork.sol` like

```
    constructor(
        address _token_address,
        address _secret_registry,
        uint256 _chain_id,
        uint256 _settlement_timeout_min,
        uint256 _settlement_timeout_max
-       address _depreacation_executor
    )
```

**Comment by pirapira** [comment]
But, when I remove the last argument, I need to change so many tests in `raiden-contracts`.

**Comment by pirapira** [comment]
This is done for now.  The following problems will be tracked on their own issues.
