### ISSUE TITLE
Check if order is important in settleChannel calculations for owed tokens

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#6]
https://github.com/raiden-network/raiden/pull/1286#discussion_r173966055
> This changed the semantics of the code, the order of payments is not arbitrary, the node that did not close the channel must be paid first.

Old code: `counter_net` (non-closing participant settlement token amount) was calculated first
New code: order does not matter

Why would the order matter?

**Comment by LefterisJP** [comment]
+1 I was also confused by this comment

**Comment by hackaugusto** [comment]
https://github.com/raiden-network/raiden/commit/5490633f162b985862c080a00ae7530b0234c32c

**Comment by LefterisJP** [comment]
So as discussed in rocketchat it seems this makes no difference after all. Somehow this notion was left floating around from some old comments/discussions we made back in end of 2016.

So @loredanacirstea you can safely ignore this and proceed as you were.
