### ISSUE TITLE
Use new ABI encoder in contract tests

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#60]
Soon (in ~2 versions is what Lefteris heard was told during Edcon) the old ABI encoder will be removed from solidity. Thus we should already start testing the new ABI encoder in our tests to see if there are any problems with it before we decide to officially switch to using it.

**Comment by LefterisJP** [comment]
Thanks for making an issue out of the Rocketchat conversation. Will edit the description. This is not really needed for the red eyes milestone though, right? It's something we can do but is not a hard requirements for Red Eyes?

**Comment by loredanacirstea** [comment]
Even if we include it in RedEyes, it can be something we do at a later stage (we should have a testing stage before the release anyway). You can change the milestone if you want.

**Comment by loredanacirstea** [comment]
Issues were solved with https://github.com/raiden-network/raiden-contracts/pull/87

I tested locally today, the contracts version from https://github.com/raiden-network/raiden-contracts/commit/fff8646ebcf2c812f40891c2825e12ed03cc7628 with:

```
pragma solidity ^0.4.24;
pragma experimental ABIEncoderV2;
pragma experimental "v0.5.0";
```

And all tests pass.
We already use features from the new ABI encoder. The full switch will be at `v0.5.0`.
Therefore, I think this can be closed. Please reopen if needed.
