### ISSUE TITLE
Run Raiden CI with limits (deposit limits and the number of tokennetworks)

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#602]
(to be scoped)

Currently `raiden` CI uses an unlimited version of contracts.  This issue keeps track of running similar test with smart contracts that are going to be deployed on the mainnetwork for Ithaca.

* [ ] How many token networks will be allowed on the mainnetwork on Ithaca?
* [ ] This issue should be reflected on the planning sheet.

**Comment by palango** [comment]
Current contracts have limits.
