### ISSUE TITLE
Try Solidity sources of 0.3._ on Etherscan

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#605]
Our README says, the `0.3._` version is compiled from this source https://github.com/raiden-network/raiden-contracts/blob/fc1c79329a165c738fc55c3505cf801cc79872e4/raiden_contracts/contracts/TokenNetwork.sol .

This issue keeps track of confirming that on Etherscan.

**Comment by palango** [comment]
0.3 has been removed from the repo.
