### ISSUE TITLE
Command to mint new test tokens

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#620]
There can be a command `raiden_contracts/utils/mint_tokens.py` that mints new test tokens.  An idea from @luehrsFred .

**Comment by pirapira** [comment]
There might be something useful in `workshop` repository.

**Comment by agatsoh** [comment]
I am working on this.

**Comment by christianbrb** [comment]
The scenario player should also contain a function for this (https://github.com/raiden-network/scenario-player/blob/73238a9ed6a97d0e7133a56e318d485f37eabbff/raiden/scenario_player/utils.py)

**Comment by pirapira** [comment]
This has been added.
