### ISSUE TITLE
Define a new role that can raise deposit limits

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#646]
This issue keeps track of adding a new role in TokenNetwork that can raise deposit limits.  This role can be assigned to an Ethereum address when TokenNetwork is deployed.

**Comment by pirapira** [comment]
The new address should be given similarly to how the deprecator is set.

**Comment by pirapira** [comment]
When I implement it naively, I hit
```
E           eth_tester.exceptions.TransactionFailed: deployment failed
```

**Comment by pirapira** [comment]
The runtime codesize hasn't hit the max code size.  I guess this is a gas issue.

**Comment by pirapira** [comment]
Yes, raising the block gas limit to 10M solves this particular issue.

**Comment by karlb** [comment]
There are currently no plans to increase the limits on an already deployed contract.
