### ISSUE TITLE
Consider adding time limits on tests not marked 'slow'

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#666]
When @karlb [marked slow tests](https://github.com/raiden-network/raiden-contracts/pull/665), @BOR4 suggested adding time limits on the tests that are not marked slow.

This issue keeps track of deciding whether to do that, and if yes, implementing the idea.

**Comment by pirapira** [comment]
I'll update this comment in-place while the discussion grows.

**(pro)**

* hard guarantee that the slow tests are marked `slow`

**(con)**

* when the test execution time depends on luck (due to, say, mining blocks), the result of the test becomes flaky.

**Comment by BOR4** [comment]
Yes I saw @karlb used 10 sec threshold. If you don't mark rest of tests with timeout(10) you will have to go back and do timing of each again and again as code changes.

With timeout marking once it is hit you just put mark slow and remove timeout mark.

I saw @pirapira con and I agree, but I don't think it matters too much what is the exact time. My suggestion was just so you have easy way in the future to track tests that have potential to go over 10 sec.

**Comment by pirapira** [comment]
Yeah, I think it's workable like, once we see a timeout we put 'slow'.

**Comment by pirapira** [comment]
@karlb any opinions?

**Comment by karlb** [comment]
Different machines have different execution speeds, so if we use a fixed timeout, the person with the slowest hardware will always have to add the `slow` markers. It will get even more annoying if we have the timeouts turned on for travis, too.
I'm not sure have specific timeouts is easier to handle then running `pytest --durations` whenever tests get unpleasantly slow and marking the slowest tests at that time.

**Comment by pirapira** [comment]
@BOR4 what's the worst scenario if we don't put the timeouts?

**Comment by BOR4** [comment]
I believe that every now and then someone will have to go through tests and mark new tests with slow mark.

Otherwise over some time running tests with slow and without it will basically be the same.

**Comment by pirapira** [comment]
I see.  I've set a reminder in four months to check if the `slow` labels are functioning.  If not, I'll raise an issue and ping both of you.

**Comment by pirapira** [comment]
I have to check if the `slow` labels are correct.

**Comment by pirapira** [comment]
There are no new slow tests.
