### ISSUE TITLE
get_contracts_deployed() sounds too active; should be fetch_deployment_data()

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#671]
"get contracts deployed" sounds to me like sending a transaction to deploy contracts.  The function does not do that.  Instead it just finds the deployment data in the filesystem.

**Comment by pirapira** [comment]
This function is also used out of the project. Don't forget documenting the change in CHANGELOG and communicating the change.

**Comment by palango** [comment]
What about `get_contract_deployment_info(...)`?

**Comment by pirapira** [comment]
@palango good idea.  That sounds a way more accurate.  Also, people looking for the old name will also find the new one (because the two names look similar enough).

**Comment by pirapira** [comment]
I'm going to solve this together with #774.

**Comment by pirapira** [comment]
#775 will fix this.

**Comment by pirapira** [comment]
Maybe nobody is using `get_contracts_deployed()` anymore.  I should check that.

**Comment by pirapira** [comment]
`raiden` still contains calls to `get_contracts_deployed()`.

**Comment by pirapira** [comment]
After https://github.com/raiden-network/raiden/pull/3703 is merged, `raiden-contracts` can remove `get_contracts_deployed()`.
