### ISSUE TITLE
Use keyword arguments for calling Solidity interface functions

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#672]
I discovered that Web3.py provides keyword arguments for Solidity interface functions:
```
token_network_registry_contract.functions.createERC20TokenNetwork(
    _token_address=custom_token.address,
    _channel_participant_deposit_limit=0,
    _token_network_deposit_limit=0,
)
```
This should be used as much as possible.

**Comment by karlb** [comment]
This is used in quite some places now. The remaining ones can be changed when the code is touched and don't need a concerted effort.
