### ISSUE TITLE
Why is the deployed token always called 'CustomToken'?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#679]
`deploy_token_contract` returns a dictionary that maps 'CustomToken' to the address of the token contract.  Shouldn't the dictionary map the specified name of the contract like 'TestToken' below?

```
    deployed_token = deploy_token_contract(deployer, tokens, TOKEN_DECIMALS, 'TestToken', 'TTT')

    token_address = deployed_token['CustomToken']
```

**Comment by pirapira** [comment]
I guess the names given in the command line options should be used.

**Comment by pirapira** [comment]
And does anybody rely on this particular naming?

**Comment by karlb** [comment]
There's no specific meaning to this name. It's just default value for the `token_type` parameter.
