### ISSUE TITLE
why not let channel_identifier be unique ?

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden-contracts#68]
why not let `channel_identifier=sha3(participant1,participant2,address(tokenNetwork) `?
so  channel identidifier can be used to as the id of a channel.  I thinks is useful for implementation of raiden network. 

if  `channel_identifier=sha3(participant1,participant2)`, there will be many channels with the same identifier, so we have to use `channel_identifier` and `tokenNetwork` as the id of a channel.

**Comment by loredanacirstea** [comment]
@nkbai , we have limited the number of channels. At the moment, two nodes in the system can only have one channel between them.
Please refer to https://github.com/raiden-network/spec/issues/55 and add there any pro's and con's that you have regarding our approach.
I will close this issue for now, as this is a `spec` related decision.

For the record, going from multiple channels between two nodes to only one was implemented in this PR: https://github.com/raiden-network/raiden-contracts/pull/58

**Comment by nkbai** [comment]
```
    function getChannelIdentifier(address participant, address partner)
        pure
        public
        returns (bytes32)
    {
        require(participant != 0x0);
        require(partner != 0x0);

        // Participant addresses must be different
        require(participant != partner);

        // Lexicographic order of the channel addresses
        // This limits the number of channels that can be opened between two nodes to 1.
        if (participant < partner) {
            return keccak256(participant, partner,address(this));
        } else {
            return keccak256(partner, participant,address(this));
        }
    }
```

**Comment by nkbai** [comment]
@loredanacirstea   return keccak256(participant, partner,address(this));
this is what i mean, two partners can only open one channel on the same token.

**Comment by loredanacirstea** [comment]
> `channel_identifier=sha3(participant1,participant2)`, there will be many channels with the same identifier

I see no problem here. For all the signed messages we always use `channel_id` + `token_network_address` + `chain_id` for replay attacks.

> two partners can only open one channel on the same token

Correct. This is intended. Please check the `spec` issue I mentioned above.

**Comment by nkbai** [comment]
I have already seen these `spec` above, 
for example:
when i want to close a channel:
`PATCH /api/<version>/channels/<channel_address>`
this channel_address should be the channel_identifier above.

and if A and B open two channels on Token1 and Token2, they will have two channels with the same `channel_identifier`.
it's  confused for users. why not make  `channle_ideitifer` be unique?  and it follows all your `spec`

**Comment by loredanacirstea** [comment]
@nkbai , the Raiden APIs will also be changed and the TokenNetwork contract address will be added. 

What you propose adds no benefit to the smart contract itself. The smart contract knows its address and there is no confusion in its logic. I think adding the contract address to the `channel_identifier` is redundant, as our goal with the contracts is to simplify logic.

Any other confusion can be handled outside of the contract. E.g. API paths that are clear. If something like `PATCH /api/<version>/<token_network_address>/channels/<channel_identifier>` is not clear enough, you can propose us to work with `keccak256(channel_identifier, token_network_address)` in the Raiden client implemention. Because we are starting to integrate the new contracts there.

**Comment by nkbai** [comment]
@loredanacirstea if channel_identifier=sha3(participant1,participant2,tokennetworkaddress), then all the recover.. function (for example recoverAddressFromBalanceProof), doesn't need verify address(this) . I think my method would save more gas.
```sol
    function getChannelIdentifier(address participant, address partner)
        pure
        public
        returns (bytes32)
    {
        require(participant != 0x0);
        require(partner != 0x0);

        // Participant addresses must be different
        require(participant != partner);

        // Lexicographic order of the channel addresses
        // This limits the number of channels that can be opened between two nodes to 1.
        if (participant < partner) {
            return keccak256(abi.encodePacked(participant, partner,address(this)));
        } else {
            return keccak256(abi.encodePacked(partner, participant,address(this)));
        }
    }

 function recoverAddressFromBalanceProof(
        bytes32 channel_identifier,
        bytes32 balance_hash,
        uint256 nonce,
        bytes32 additional_hash,
        bytes signature
    )
        view
        internal
        returns (address signature_address)
    {
        bytes32 message_hash = keccak256(abi.encodePacked(
            balance_hash,
            nonce,
            additional_hash,
            channel_identifier,
           // address(this), no need this address  because channel_identifier already contains this information.
            chain_id
        ));

        signature_address = ECVerify.ecverify(message_hash, signature);
    }
```
this id have two advantages:
1. save gas (for cooperativeSettle,updateNonClosingBalanceProof,setTotalWithdraw)
2. more friendly for raiden app implementation. only one variable channel_identifier would identify a channel, no need of tokennetwork address
