### ISSUE TITLE
Gas cost optimization - storage pointer computation for mappings

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#7]
Not urgent now, but should be considered after we are completely settled on the contracts ABIs.
Any other gas cost optimization suggestions or issues should be gathered here for now.

- https://github.com/raiden-network/raiden-contracts/commit/921c006a8fac5e556e238808667b48016b4c2bab#r28074132
> How clever is the solidity compiler for repeated expressions like channels[last_channel_index]? Will it notice that this is the same storage location and compute the pointer only once?

**Comment by loredanacirstea** [comment]
tl;dr @hackaugusto , seems it computes the pointer every time :|. good observation.  

```js
   function use(uint256 index) public {
        channels[index].settle_timeout = 5;
        channels[index].settle_timeout = 5;
    }
    
    // saves 109 gas
    function use2(uint256 index) public {
        Channel storage channel = channels[index];
        channel.settle_timeout = 5;
        channel.settle_timeout = 5;
    }
```

`use2` - 31756
```
358 SSTORE
359 POP
360 PUSH1 05
362 DUP2
363 PUSH1 00
365 ADD
366 DUP2
367 SWAP1
368 SSTORE
369 POP
```

`use` - 31865
```
567 SSTORE
568 POP
569 PUSH1 05
571 PUSH1 00
573 DUP1
574 DUP4
575 DUP2
576 MSTORE
577 PUSH1 20
579 ADD
580 SWAP1
581 DUP2
582 MSTORE
583 PUSH1 20
585 ADD
586 PUSH1 00
588 SHA3
589 PUSH1 00
591 ADD
592 DUP2
593 SWAP1
594 SSTORE
595 POP
```

**Comment by hackaugusto** [comment]
Humm, interesting, thanks for investigating it :)

**Comment by LefterisJP** [comment]
@loredanacirstea @hackaugusto  In defense of solidity, there are optimizations. You just need to activate them ;)

Example is with `solc v0.4.20`

Example contract:

```solidity
contract foo {

    struct Channel {
        uint256 settle_timeout;
    }

    mapping(uint256 => Channel) channels;
    function use(uint256 index) public {
        channels[index].settle_timeout = 5;
        channels[index].settle_timeout = 5;
    }

    function use2(uint256 index) public {
        Channel storage channel = channels[index];
        channel.settle_timeout = 5;
        channel.settle_timeout = 5;
    }
}
```

> solc --gas TEST.sol

```
Gas estimation:
construction:
   106 + 57800 = 57906
external:
   use(uint256):        25382
   use2(uint256):       25295
```

> solc --optimize --gas TEST.sol

```
Gas estimation:
construction:
   82 + 32400 = 32482
external:
   use(uint256):        20231
   use2(uint256):       20209
```


With optimization use2 is still a tinty bit better but only by `22` gas.

**Comment by loredanacirstea** [comment]
Yes, last time we agreed to not use the optimizations. I know they are better now, but I don't know the current status - if they are entirely safe. We will need to check this out around deployment time.

**Comment by LefterisJP** [comment]
Can't complan about the compiler if you disable optimizations. Sure ... to be 100% safe that we never run into a compiler bug (i.e. an optimization which also changes the meaning of the code in a subtle way) we can just not use optimizations.

But then we pay the gas price.
