### ISSUE TITLE
Switch to a single ServiceRegistry contract for all Token Networks

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden-contracts#734]
Hey @yoichi I started work on integrating the services registry in the raiden client: https://github.com/raiden-network/raiden/issues/3467 and I would like to discuss the interface with this issue.

## Problem Definition

Looking at the `ServicesRegistry` [contract](https://github.com/raiden-network/raiden-contracts/blob/32621a089a51064121c68a14a21a3c194703e3c6/raiden_contracts/contracts/services/ServiceRegistry.sol) I see something that I don't really like and want to ask on the logic behind it.

It seems we now got one `ServicesRegistry` per token. Why is that? Why should we require people to deploy a new `ServicesRegistry` for each time a new TokenNetwork is created? Just like we got only one `SecretRegistry` I would expect that we got only one `ServicesRegistry`.

Naturally there can be services that monitor only a specific token network but that mapping can be held inside the state of a single contract instead of creating a new contract for each new Token Network.

## Proposal

Change the `ServicesRegistry` contract to have the following interface:

```solidity
    constructor() public
    function deposit(address token_address, uint amount) public
    function setURL(address token_address, string memory new_url) public
    function serviceCount(address token_address) public view returns(uint)
```

That would mean that there should be an extra layer of mapping from token address to state for the internal state of `deposits`, `urls`, `service_addresses`

**Comment by pirapira** [comment]
That's fine for me.  @palango @karlb what do you guys think?

**Comment by palango** [comment]
In my opinion the `ServicesRegistry` is only supposed to work with one token, namely the ` RDN` token. The reason for this is that we want one list of services for all token networks, but all of them should stake tokens in order to get a slot in the registry.

@LefterisJP @pirapira Does that make sense?

**Comment by LefterisJP** [comment]
Hmm I think you are confusing the two tokens. `RDN` is the payment token, but you also need to know which token networks is each service provider providing services for.

For example I may be a service provider only for the DAI token network. I need to be registered as such.

**Comment by pirapira** [comment]
@LefterisJP 

> Why should we require people to deploy a new ServicesRegistry for each time a new TokenNetwork is created?

Not really.  A new ServicesRegistry is needed when people start using new tokens for registering services (in an auction or a fixed registration fee).


> you also need to know which token networks is each service provider providing services for.

If you need to know that, I can add the info.  Currently I have very vague idea what ServiceRegistry is supposed to do.

**Comment by pirapira** [comment]
@palango 

> we want one list of services for all token networks, but all of them should stake tokens in order to get a slot in the registry.

I think that works for Ithaca.  I don't know what happens when the number of TokenNetworks goes unlimited.

**Comment by palango** [comment]
> but you also need to know which token networks is each service provider providing services for.

I never thought about that, but I always assumed that services should support all token networks.
As for your proposal:
- For the MS this won't change anything, as the MonitorRequest is broadcasted anyways.
- For the PFS there is an `/info` endpoint which can solve the problem presented above.

**Comment by LefterisJP** [comment]
@pirapira @palango 

I see I probably misunderstood the `token_address` argument in the constructor being that of the token network that is being monitored by the services.

I propose to change the naming and add docstrings accordingly to make it clearer. Change name to `token_for_payment` or something similar.

Also I would still insist we include the token network address each service monitors. Better to think ahead and be future-proof rather than get bitten by this in the future.

I don't think all services will monitor all token networks. This makes no sense from a business point of view for the services.

**Comment by palango** [comment]
> Also I would still insist we include the token network address each service monitors. Better to think ahead and be future-proof rather than get bitten by this in the future.

So what happens if a service want's to provide services for multiple/all token networks? (Something I expect to be quite common in the beginning). Does it have to stake for each token network, can it register on multiple (but then we need to provide ways to remove this as well).

**Comment by LefterisJP** [comment]
> So what happens if a service want's to provide services for multiple/all token networks? (Something I expect to be quite common in the beginning). Does it have to stake for each token network, can it register on multiple (but then we need to provide ways to remove this as well).

I would expect that you "stake" only RDN.

But you register yourself as a service for a specific set of token networks.

And yes we also need a de-register function.

**Comment by pirapira** [comment]
@LefterisJP 

If you as a service provider want to watch three TokenNetworks, is the registration fee three times more expensive, or you have to register three times?

What if you volunteer to monitor all TokenNetworks?  Is the registration fee much more expensive than monitoring one?

**Comment by pirapira** [comment]
@LefterisJP will you open new issues for tracking the issues that were discovered here?  "A switch to a single ServiceRegistry" is somehow already done.

**Comment by LefterisJP** [comment]
> I feel these changes would make stuff a lot harder in the beginning for an unknown benefit far in the future (and something that's already possible by other means). So I'd argue against these changes.

@palango 

We are talking about defining the interface of a long-living contract. We have to think about these interfaces and think about them in a future-proof way.

I don't see how this will make things harder, as long as we agree on the interface. It's not an unknown benefit far in the future. Services won't work by monitoring every single Token Network into existence. That makes no sense. Why would I as a service monitor monitor networks whose tokens have no value for me? What if I don't have the capacity to do so? 


> (and something that's already possible by other means)

Can you elaborate?

@pirapira

**Comment by pirapira** [comment]
* Should some/all services monitor every TokenNetwork? --> https://github.com/raiden-network/spec/issues/221

**Comment by pirapira** [comment]
* Should ServiceRegistry contract keep track of which service supports which TokenNetwork? --> https://github.com/raiden-network/raiden-contracts/issues/737

**Comment by pirapira** [comment]
* Should it be possible to de-register from ServiceRegistry contract? https://github.com/raiden-network/raiden-contracts/issues/738

**Comment by palango** [comment]
> Can you elaborate?

- For the MS the added interface provide no advantages, as the MonitorRequest is broadcasted. If this is deemed important we could also add a `info` endpoint for the MS which would provide the same information.

- For the PFS there is an `/info` endpoint which can solve the problem presented above.

Finally, by letting all services choose the *profitable* token networks, we might create a incentive problem for running services for the smaller networks.

**Comment by LefterisJP** [comment]
@pirapira All these questions are connected. I don't see a point in opening different issues and just making the conversation harder to follow.

I would only open different issues once we decide on what we want to do. Right now we are at the point of discussing.

@palango 

> Finally, by letting all services choose the profitable token networks, we might create a incentive problem for running services for the smaller networks.

This incentive problem exists. Unless you force all people running a service to watch all possible token networks. In which case you also have to talk about enforcement. How can you be sure the services do indeed monitor all token networks? And if they are supposed to how can you be sure they do? How do you enforce it? And do we do it right now?


> For the MS the added interface provide no advantages, as the MonitorRequest is broadcasted. If this is deemed important we could also add a info endpoint for the MS which would provide the same information.
>For the PFS there is an /info endpoint which can solve the problem presented above.

Aha so you say that as a service you don't need to register for a specific token, but you can just advertise it through your API. All right that is good. I get your point here.

----

So thinking more on this.

The only reason to need to register which tokens you monitor in the services contract is enforcement. If we can't or not plan to enforce them then indeed it makes no sense.

But then as I said above we need to discuss on what guarantees you get from a service provider registered in the registry. Does it mean he will monitor all token networks? If yes how can we enforce this?

**Comment by pirapira** [comment]
@LefterisJP 

> I don't see a point in opening different issues

Don't worry, I will turn them into... ADRs!

> Right now we are at the point of discussing.

Go on if you will.

**Comment by pirapira** [comment]
The design space expanded a lot, and maybe this is not a good starting point anymore.  Moving the discussion to a private space: https://github.com/raiden-network/team/issues/363
