### ISSUE TITLE
How can services get deposits paid back from the ServiceRegistry contract?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#738]
@LefterisJP https://github.com/raiden-network/raiden-contracts/issues/734#issuecomment-472420155

> And yes we also need a de-register function.

**Comment by LefterisJP** [comment]
We would need a de-register function for sure, right? I may want to stop functioning as a service provider at some point. Then I would also like to get my deposit back and exit the system.

**Comment by pirapira** [comment]
Now it's unclear whether there is a single design for ServiceRegistry.
