### ISSUE TITLE
Update contribution guide to explain the structure of the repo

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden-contracts#745]
Currently it's a bit confusing and not very clear which files to change when making changes to the contracts and the current [Contrubution.md](https://github.com/raiden-network/raiden-contracts/blob/master/CONTRIBUTING.md#location) seems outdated. 

The current document should be updated to explain which source files to edit when making changes and to give an overview of the general structure of the repo.

**Comment by pirapira** [comment]
> which files to change when making changes to the contracts and the current Contrubution.md seems outdated.

I can fix this easily.

> to give an overview of the general structure of the repo.

I haven't found an overview.  After making enough simplifications and refactoring, there will emerge some easy-to-explain structures.

**Comment by pirapira** [comment]
`RELEASE.rst` is also outdated.  It still mentions `raiden_contracts/contracts`, which no longer exists.

**Comment by pirapira** [comment]
Also, `    bumpversion --config-file ./.bumpversion_contracts.cfg [PART]` fails for missing `raiden_contracts/contracts`.
