### ISSUE TITLE
not enough ticks are shown in Travis console

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#750]
As @palango [noticed](https://github.com/raiden-network/raiden-contracts/pull/749#pullrequestreview-216076762) Travis consoles sometimes show less than expected number of tick signs for successful tests.  There should be as many green ticks as the test cases.

**Comment by karlb** [comment]
Instead of doing this, we should switch to CircleCI to be consistent with the other Raiden repos.
