### ISSUE TITLE
TokenNetwork on test networks can allow much shorter settlement periods for demos?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#792]
I heard every test that involves channel settlement needs hours of running time because of the minimum settlement period.  This issue considers allowing much shorter settlement periods on test-networks.

**Comment by err508** [comment]
The scenario player allows users to deploy a fresh token contract every time a scenario is ran. This might be a good hook to enable this.

**Comment by karlb** [comment]
We do have contracts with shorter limits on the testnets, now. See also https://github.com/raiden-network/raiden-contracts/issues/822.
