### ISSUE TITLE
Use error strings in smart contracts

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden-contracts#81]
## Description 
Since solidity 0.4.22 error strings are supported for revert and require:
```
pragma solidity ^0.4.22;

contract VendingMachine {
    function buy(uint amount) payable {
        if (amount > msg.value / 2 ether)
            revert("Not enough Ether provided.");
        // Alternative way to do it:
        require(
            amount <= msg.value / 2 ether,
            "Not enough Ether provided."
        );
        // Perform the purchase.
    }
}
```
Adding this to the smart contract will make it easier to debug where things go wrong in a function. It also makes the terrible work flow of removing `require`s to figure out which require is failing obsolete. 

## Tasklist 
- [x] SecretRegistry - no `require`s
- [x] TokenNetworkRegistry (#1498)
- [ ] TokenNetwork (https://github.com/raiden-network/raiden-contracts/pull/1499)
- [x] Controllable (#1492)
- [x] MonitoringService
- [x] OneToN
- [x] ServiceRegistry
- [x] UserDeposit

**Comment by LefterisJP** [comment]
@loredanacirstea Do you think you can add them in this contract change (red eyes testnet 4)? I would say it's good to take advantage of the redeployment to include them.

**Comment by loredanacirstea** [comment]
Yes, added the milestone now.

**Comment by loredanacirstea** [comment]
Just some notes:

- revert error messages are not currently supported by web3.py - https://github.com/ethereum/web3.py/issues/941. When they will be supported, in order to get them, one would need to `eth_call` the contract function and get the encoded error.
- there are EIPs in discussion about standardizing status codes for errors (similar to http), that can also be handled in the EVM - https://eips.ethereum.org/EIPS/eip-1066; This is worth following in my opinion, as it could improve the automatic interaction between smart contracts.

Aside from these mentions, I am ok with just using some error strings right now and re-evaluating them after standards are clarified.

**Comment by pirapira** [comment]
P2 because I heard error strings would have saved our time today.

**Comment by pirapira** [comment]
If we don't hit the bytecode length after enabling cooperativeSettle(), this will be definitely implemented.  So the next task is to try enabling the cooperativeSettle() locally and see if the compilation still works.

**Comment by pirapira** [comment]
Even if we recover `cooperativeSettle()`, we can still add at least a two-character message to each `require`.

**Comment by pirapira** [comment]
If we recover `cooperativeSettle()` and add a two-character comment on each of `require`, the runtime codesize will be 28835 bytes, which exceeds the deployable limit of 24576 bytes.

**Comment by pirapira** [comment]
Whether we optimize or not, any message that fits 32 bytes seems to compile into the samely sized runtime code.  So no need to go for cryptic "a" "b" "c" style messages.

**Comment by pirapira** [comment]
I’ll just add somewhat recognizable comments under 32 bytes.

**Comment by pirapira** [comment]
This depends on #401.

**Comment by palango** [comment]
Just tried the old )PR again, we're still running into code size issues

**Comment by karlb** [comment]
See https://github.com/raiden-network/raiden-contracts/issues/1435 for more space saving.
