### ISSUE TITLE
deploy versions with shorter settlement periods on test nets? Or remove limits altogether?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#822]
Some tests (especially scenarios) are taking more time than necessary because there is a hard lower limit on the length of settlement periods.  This issue keeps track of deploying tweaked smart contracts on test networks so the tests can be faster.

**Comment by pirapira** [comment]
It would save time for @czepluch .  @karlb mentions there should also be a deployment that's identical to what would be on the mainnet.  A decision has to be made about the ABI of how to access the two different kinds of deployment. Maybe I should think about it together with https://github.com/raiden-network/raiden-contracts/issues/524

**Comment by pirapira** [comment]
Also, we should consider why these settlement periods need to be enforced in the smart contract.  Ideally, clients can see the settlement period of each channel before making a deposit to any of these.   Then, we don't need global limits on the settlement periods.

**Comment by pirapira** [comment]
I got a feedback from @Dominik1999 .  I'll try to get remove the global "min" limit. If I see a good counter-argument, I'll think again.  This helps faster testing.

**Comment by pirapira** [comment]
@hackaugusto is against allowing users to set irrationally low settlement periods on the mainnet.

**Comment by hackaugusto** [comment]
@pirapira This is not 100% my opinion, I'm just expressing the result of previous discussions, please refer to:

https://github.com/raiden-network/spec/issues/16
https://github.com/raiden-network/raiden/issues/383
https://github.com/raiden-network/raiden/issues/864
https://github.com/raiden-network/team/issues/52#issuecomment-414354471 and https://github.com/raiden-network/team/issues/52#issuecomment-414610110

And changes related to this value (just for reference, not that important):

https://github.com/raiden-network/raiden/pull/1750
https://github.com/raiden-network/raiden/issues/110
https://github.com/raiden-network/raiden/pull/1777

**Comment by pirapira** [comment]
@Dominik1999 are you happy with calling TokenNetwork.register() on your own, with a smaller minimum settlement period?

**Comment by czepluch** [comment]
Ping @Dominik1999 .

IMO, I think it's fine to manually make the call. But I would love to have this ready ASAP, as it would significantly lower the time it takes to run scenarios, which is useful while we're writing and experimenting with scenarios.

**Comment by Dominik1999** [comment]
Yes that seems like a good approach

**Comment by pirapira** [comment]
> TokenNetwork.register() on your own, with a smaller minimum settlement period?

Sorry I was wrong. Calling `createERC20TokenNetwork` is not enough.  A special TokenNetworkRegistry is needed.  That will be placed under `data_0.13.0_shorter_settlement/...`.

I'll write up #828 and agree with other teams, and then implement it.

**Comment by Dominik1999** [comment]
Can we close this issue? Or is there some input/output missing?

**Comment by LefterisJP** [comment]
Why close it? It has not been implemented afaik.

**Comment by karlb** [comment]
We work with shorter settle timeouts on the testnets for a while now. When we need the "real" mainnet timeouts, we can just release a set of contracts with full timeouts before the release. With https://github.com/raiden-network/raiden-contracts/pull/1224 done, this is easy enough.
