### ISSUE TITLE
EndpointRegistry - add basic unit tests

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#84]
We decided to keep the `EndpointRegistry` contract for now - https://github.com/raiden-network/raiden-contracts/issues/82, we need to add some basic unit tests to make sure it works.

**Comment by hackaugusto** [comment]
https://github.com/raiden-network/raiden/blob/587013d3b7aa930b617b2b98091d2206fe3976f4/raiden/tests/smart_contracts/test_endpointregistry.py
