### ISSUE TITLE
Is it possible Recreate a channel to prevent parnter to unlock?

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden-contracts#85]
1.A create a channel with B on RDN
2.A send 100 RDN to B, but without sending B the Unlock Message.
3. B call SecretRegistry, register the secret.
3. A close channel
4. settle channel 
5. re create a channel with B with very small settle time ,like 6 blocks
6. close and settle the new channel.

if B doesn't monitoring the channel event between step 4 and step 6(that is about 7 blocks time).
then B will lose the 100 RDN.

A short time DoS attach to B, only less than 2 minutes, will make B lose 100 RDN.
am I right?

**Comment by loredanacirstea** [comment]
> Is it possible Recreate a channel to prevent parnter to unlock?

It should not be. Can you explain in more detail how this would happen? (e.g. using the data structures from the contract, explain the flow)

> if B doesn't monitoring the channel event between step 4 and step 6(that is about 7 blocks time).
then B will lose the 100 RDN.

If these tokens (from the first channel, step 1) are locked in the channel through the balance proof's `locked_amount`, and therefore can only be taken out of the contract by calling `unlock`, I don't see how you would lose them in this scenario. Can you be more explicit?

> A short time DoS attach to B, only less than 2 minutes, will make B lose 100 RDN.
am I right?

Discussion for changing the settlement window minimum: https://github.com/raiden-network/spec/issues/16.
But I think this is a different discussion than your original question, unless I misunderstood.

**Comment by LefterisJP** [comment]
@nbkai Note that there are 2 mappings. 

One is a [mapping](https://github.com/raiden-network/raiden-contracts/blob/87d49639fb647da85861cd6e8ba6b8a57aed0e8a/raiden_contracts/contracts/TokenNetwork.sol#L597) from the `channel_identifier` to unlock data.

And the [second](https://github.com/raiden-network/raiden-contracts/blob/87d49639fb647da85861cd6e8ba6b8a57aed0e8a/raiden_contracts/contracts/TokenNetwork.sol#L601) is a mapping located inside the unlock data from the locksroot to the locked amount.

Since the locksroot is going to always be different there is no way to lose locks from old channels.

**Comment by nkbai** [comment]
@LefterisJP channel_identifier_to_unlock_data will be modified when settle a channel.
because when recreate a channel,the new channel will have the same identifier as the previous.
so when settle this one, the old channel_identifier_to_unlock_data will be overlapped.

**Comment by loredanacirstea** [comment]
Unlock data for a channel is stored in `channel_identifier_to_unlock_data[channel_identifier]`. If the channel is closed and reopened multiple times, yes, the unlock data will be stored in the same place. 

Each `locked_amount` is stored at a separate `locksroot` in the mapping: `channel_identifier_to_unlock_data[channel_identifier].locksroot_to_locked_amount[locksroot] = locked_amount`. Each `locksroot` will be different, so there is no overlap. 

`channel_identifier_to_unlock_data[channel_identifier]` is not deleted between channel settle and another channel open, so all the `unlock` data should still be valid and should permit token retrieval.

@nkbai , does this answer your question?

**Comment by nkbai** [comment]
@loredanacirstea  yes, thanks very much.

**Comment by loredanacirstea** [comment]
Great! And thank you for looking into the protocol in detail. 
After the above discussion, I have added your question as a unit test case that we need to write: https://github.com/raiden-network/raiden-contracts/issues/88.
