### ISSUE TITLE
Contracts should check chain_id in signed balance proofs, withdraw proofs etc

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#855]
For this, the constructors should take a `uint256 chain_id` argument and store the value in the storage.

This is a breaking change regarding the API of smart contracts.

As an exception, SecretRegistry need no updates (the inputs there are replayable).

**Comment by LefterisJP** [comment]
Hmm but the chain id is part of the signed data that creates the signature, so it should be implicitly checked I believe.

**Comment by pirapira** [comment]
@LefterisJP You're right that the chain-id in Ethereum transactions are checked, but `chain_id` in balance proofs, withdraw proofs etc are not checked against anything right now.

**Comment by pirapira** [comment]
I changed the title to make the target clearer.

**Comment by LefterisJP** [comment]
Aha so you mean to make sure that the chain id corresponds to the id of the network that the contract is deployed on I understand now

**Comment by pirapira** [comment]
Yes, otherwise, balance proofs will be replayable easier on different chains.

**Comment by pirapira** [comment]
We can already deploy a `chain_id` contract that executes the `0x46` instruction.  When https://ethereum-magicians.org/t/eip-1344-add-chain-id-opcode/1131 lands, this contract starts working.

**Comment by LefterisJP** [comment]
@karlb Are you sure this issue should be closed only after #877? Isn't this issue for all the contracts?

**Comment by karlb** [comment]
According @pirapira (in #877), the other contracts already check the chain_id:

> The other contracts were checking the chain_id somehow. So this PR closes #855.

**Comment by pirapira** [comment]
Yes, it's my intention to close this issue.
