### ISSUE TITLE
Fix `keccak256` and fallback function breaking changes for solc 0.5.0

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#86]
The following 0.5.0 breaking changes currently affect the contracts:

- fallback functions must be `external` (https://github.com/ethereum/solidity/blob/develop/Changelog.md#0417-2017-09-21)
- `keccak256` can only be used with a single `bytes` argument; `abi.encodePacked` can be used to tightly pack arguments (https://github.com/ethereum/solidity/blob/develop/Changelog.md#0424-2018-05-16)

**Comment by LefterisJP** [comment]
Can you provide a link to all the features of solidity 0.5.0 that you want to account for? With 0.5.0 not yet released we can't really consider this issue complete.

**Comment by loredanacirstea** [comment]
@LefterisJP , copied the PR description here.
