### ISSUE TITLE
Extend etherscan_verify.py so it works with 0.4.0 on Goerli

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#864]
Currently, etherscan_verify only works with `contracts_version == None` (it doesn't even take the `--contracts-version` option).  This issue keeps track of extending the script so it works with contracts_version == 0.4.0 on Goerli chain (chain-id == 5).

**Comment by pirapira** [comment]
While testing this script, I should be able to convince Etherscan that these contracts are deployed from certain sources.

**Comment by pirapira** [comment]
Or, just using Etherscan from a web browser is acceptable in this case.

**Comment by karlb** [comment]
There's no need to verify 0.4.0, anymore. For new contracts, we verify them right after deployment.
