### ISSUE TITLE
Update to eth-tester for Istanbul compatibility

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-contracts#868]
According to the [changelog](https://github.com/ethereum/eth-tester/blob/master/CHANGELOG) this sets the default VM rules to Constantinople

**Comment by pirapira** [comment]
eth-tester 0.1.0-beta.39 causes some version inconsistency https://github.com/raiden-network/raiden-contracts/pull/876#issuecomment-484396973 .  The next step: somehow figure out the versions, or wait for the 0.1.0 release.

**Comment by pirapira** [comment]
`web3` package up to `4.9.2` has version conflicts with the new `eth-tester`.  `web3` from `5.0.0a1` has a circular dependency `web3 => ethpm => web3`.

**Comment by pirapira** [comment]
But I don't care about the circular dependency.  So filing a PR: https://github.com/raiden-network/raiden-contracts/pull/891

**Comment by pirapira** [comment]
I'll wait till `web3>=5.0.0` is available (maybe beta is good enough).
