### ISSUE TITLE
Add more test values for the channel settle token amounts.

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#89]
Add more cases to `channel_test_values.py` - testing channel settle token amounts.

**Comment by LefterisJP** [comment]
Perhaps this is where you could use something like property testing to test ranges of values?

**Comment by loredanacirstea** [comment]
Added values manually for known edge cases in
https://github.com/raiden-network/raiden-contracts/commit/8decf565ff1098662c94b148cdb1b041aba6ee19#diff-155b1944c9c54cfb5ecab176aefe584d
https://github.com/raiden-network/raiden-contracts/commit/bf56d07c9207f7330e6c169d491cf560647e36df#diff-155b1944c9c54cfb5ecab176aefe584d

This can be closed. We can open other issues for  adding more settlement calculations tests.
