### ISSUE TITLE
Add an FAQ entry about 'block gas exceeded'

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#914]
Maybe the reason is `--gas-limit` with a too big argument.

**Comment by agatsoh** [comment]
Just putting your statements as it is so that we dont forget 

> when you specify –gas-limit, the gas estimation doesn’t run, and the specified value 60000000 is encoded in the Ethereum transaction directly.
> And that’s bigger than block gas limit so geth complains.
