### ISSUE TITLE
enable mypy strict mode

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#918]

**Comment by pirapira** [comment]
Try enabling checks one by one:

https://github.com/raiden-network/raiden-services/blob/master/setup.cfg#L29

**Comment by pirapira** [comment]
In `--strict`, all generic types require type parameters.

**Comment by pirapira** [comment]
Also `mypy --strict` requires annotating many classes and functions in Web3.py.

**Comment by karlb** [comment]
The `--strict` flag is extremely strict (at the moment it's 1150 errors). It's probably not worth making the code adhere to it fully, but we can enable a few more checks in the `setup.cfg`. We're currently missing
```
# disallow_any_generics = True
# disallow_subclassing_any = True
# disallow_untyped_calls = True
# disallow_incomplete_defs = True
# disallow_untyped_decorators = True
# no_implicit_optional = True
# warn_redundant_casts = True
# warn_return_any = True
# no_implicit_reexport = True
```
