### ISSUE TITLE
Naming consistency of different channelsettle functions in token_network.sol

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-contracts#93]
While refactoring the ChannelSettle events, I found the variable names for amount to be settled a little confusing: there is `participantx_transferred_amount` in the `settleCannel` function and `participantx_balance` in `cooperativeSettle`. Is there a reason for the difference? If not, I'd refactor to `participantx_balance`, as `transferred_amount` makes more sense to me as a variable name for the off chain logic.

**Comment by loredanacirstea** [comment]
@err508 , `participantx_balance` should remain as it is for `cooperativeSettle`. `participantx_transferred_amount` was used in `settleChannel` due to the local variables limit. I just reused an existing variable.

**Comment by err508** [comment]
I see!
