### ISSUE TITLE
Exclude setup.py from Codecov measurements

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#959]
CodeCov is still complaining about the coverage in `setup.py`.
https://codecov.io/gh/raiden-network/raiden-contracts/compare/909ba9683e7b601c0fcb26bc0de20f0f490f14e2...750bd6b6d45f742eb9de1761e801166af91dfa00

This issue keeps track of stopping the coverage measurements in setup.py.   Somehow #724 was closed too soon.

**Comment by karlb** [comment]
This is not enough of a problem to keep the ticket. If anyone wants to fix this, feel free to do so.
